### ISSUE TITLE
[Invalid] [Spell] [Proficiencies] [Weapon] Skills

### ISSUE THREAD

**Issue by mclgv** [OmegaWoWeu/Decades#100]
Description: Invalid information while displaying weapons.

How to reproduce bug: Take a weapon that you didnt learn skills.

How it should work: It must warn players with red warning

Screenshots:
![wowscrnshot_030219_130958](https://user-images.githubusercontent.com/48056057/53681227-80fa8080-3cf7-11e9-891e-909ed25ad8b5.jpg)

Relevant AddOns used: none

Source: Aranel on Omegawow

**Comment by blzee** [comment]
Delete your cache.
