### ISSUE TITLE
[Dungeon] Dire maul East  - [Npc] Old ironbark

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#101]
Description: Your goal in the Conservatory is a door at the very north. To open it, someone will have to talk to Old Ironbark, who will then rampage and bust the door down. The old ironbark is not there . the weaken version of it is there but after you kill zervin thorn hoof it will dissappear and never come back.
How to reproduce bug:
Old Ironbark becomes Ironbark the Redeemed after Zevrim Thornhoof is killed. He will then be able to break open the door leading to the final part of the instance. but he doesnt appear
How it should work:
old ironbark should be there in order to talk with players . He will then be able to break open the door leading to the final part of the instance.
Screenshots:
![wowscrnshot_030219_161924](https://user-images.githubusercontent.com/47177389/53682032-05083480-3d07-11e9-8e3f-b0391319bf81.jpg)
![wowscrnshot_030219_160151](https://user-images.githubusercontent.com/47177389/53682047-29641100-3d07-11e9-885c-5005e5b47ec6.jpg)

this is the place where he should be But as you see he isnt.
Relevant AddOns used: -

Source:Bordoo

**Comment by GoldenE89** [comment]
Found the same issue just now, it needs for dungeonmaster achi so, it needs a hotfix.

**Comment by mclgv** [comment]
++

**Comment by MarceloTheOne** [comment]
Can't reproduce, npc is there.
