### ISSUE TITLE
Moonkin Form

### ISSUE THREAD

**Issue by Warmanesucks** [OmegaWoWeu/Decades#103]
Description: Moonkin Form

How to reproduce bug: If you try to auto attack something while in this form, the "disform" ( when you go back into human form from any form ) , sound is played over and over again.

How it should work: Going back to human form sound shouldn't be played when you auto attack in Moonkin Form

Screenshots:

Relevant AddOns used:

Source:

**Comment by blzee** [comment]
Trying to reproduce the bug, it’s not happening for me. Are you able to get a video of it?
