### ISSUE TITLE
Immolate into conflagrate bug

### ISSUE THREAD

**Issue by skillzlol** [OmegaWoWeu/Decades#105]
Description:
When casting Immolate after the GCD conflagrate should be a instant cast, yet there seems to be a 1 second delay. 
How to reproduce bug:

How it should work:

Screenshots:

Relevant AddOns used:

Source:

**Comment by JonasD92** [comment]
That's the blizzlike behaviour of immolate-conflagrate combo. It was just not implemented on other private servers - giving a hidden buff to destruction warlocks. 
Doing some search on google about conflagrate delay, you will see theorycrafting about what is the best thing to do during that time. 
It can also be seen on old pvp movies. Check Drakedog 9 where he usually uses the immolate - searing pain - conflagrate combo, as you can clearly see that the conflagrate button is greyed for a second after the immolate cast.

**Comment by blzee** [comment]
Invalid report.
Missing proofs/sources.

**Comment by bloodsugar** [comment]
Probably requires immolate to tick once before conflagrate being usable... my opinion with poor knowledge of warlocks
