### ISSUE TITLE
Leaving Combat Timer

### ISSUE THREAD

**Issue by zoneqt** [OmegaWoWeu/Decades#106]
Description: Hi guys , leaving combat timer without taking any actions is 5 seconds originally, on Decades it takes 6 seconds this ruins game mechanics of rogue class and make a big handicap in pvp because its not possible to restealth after gouge(improved). 
I hope this will be fixed, best regards.

How to reproduce bug: Enter combat , stop attacking and use stopwatch at same time.

How it should work:

Screenshots:

Relevant AddOns used:

Source: Experience

**Comment by Rodaxfck** [comment]
I think there is a serious bug in delays

**Comment by mclgv** [comment]
++
