### ISSUE TITLE
All Hail Roanauk!

### ISSUE THREAD

**Issue by Torranius** [OmegaWoWeu/Decades#107]
Description: quest 

How to reproduce bug: missing npc Roanauk Icemist

How it should work: Being able too talk to him and get the completion

Screenshots:
![image](https://user-images.githubusercontent.com/48279013/53871649-f36fa700-3ffc-11e9-947d-8b7e7fee5637.png)

Relevant AddOns used:

Source:

**Comment by blzee** [comment]
You still having issues with this? I’ve completed the whole wrathgate questline without issue.
