### ISSUE TITLE
[quest]  [Target: Dalson's Tears]

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#108]
Description:
for this quest you need to Go to Dalson's Tears in Western Plaguelands to locate and defeat the Cauldron Lord present there, and use its key to gain access to the cauldron. You must have the Empty Dalson's Tears Bottle with you to secure a sample of the poisons used inside the cauldron.
well, you can defeat the cauldron lord and you can get the key from it .the problem is you can not interact with the cauldron.it's unclickable.
How to reproduce bug: 
after taking the quest and killing the cauldron lord, you cant talk and turn in the quest to cauldron.

How it should work:
you should be able to talk to the cauldron and give in the quest .
Screenshots:
![123](https://user-images.githubusercontent.com/47177389/53954910-d0bcbb80-40ec-11e9-85af-2332459b4883.PNG)

Relevant AddOns used: quest helper - tomtom

Source: Gm Bordoo

**Comment by muhnow** [comment]
I was able to successfully complete this quest with no issue. So was the person that I was questing with.

**Comment by blzee** [comment]
I was able to complete the full chain on alliance side as well, anyone else having issues with this?

**Comment by blzee** [comment]
Have completed this chain twice now, I’ve seen others complete it as well. If the issue is still happening, open another report and we will go from there. Thank you for your report tho.
