### ISSUE TITLE
[ QUEST ] : A dip in the moonwell

### ISSUE THREAD

**Issue by GMShepherdOW** [OmegaWoWeu/Decades#11]
Description: The quest requires you to take a control of a robot (Robotron 300) and go to a moonwell and use a spell to drink the water.

How to reproduce bug: Take control of Robotron 300 and go to the moonwell, use the spell to drink the water, the quest doesn't complete after that.

How it should work: The quest should complete after drinking water.

Screenshots: http://prntscr.com/mdrc9y

Relevant AddOns used: /

Source: https://www.wowhead.com/quest=9433/a-dip-in-the-moonwell

**Comment by Bordoo** [comment]
well i had the same issue but when i abondoned and take it again it worked .... btw if you and your teammate are doing it together. you must take it and compelete it one by one

**Comment by OmegaWoWeu** [comment]
We were unable to reproduce the issue.
![wowscrnshot_013119_040314](https://user-images.githubusercontent.com/46454294/52027920-53aa8f00-250d-11e9-8771-1436b4699297.jpg)
