### ISSUE TITLE
[Quest] The Northern Pylon

### ISSUE THREAD

**Issue by RealZwox** [OmegaWoWeu/Decades#110]
The Pylon gives no Credit when you talk to him.

Should give you credit when you talk to the Pylon.

Im pretty sure the other Pylons are not giving credit aswell. That has to be checked.

**Comment by blzee** [comment]
Invalid report.
Missing proofs/sources.

**Comment by RealZwox** [comment]
https://www.wowhead.com/object=164955/northern-crystal-pylon#comments

Here is your source.
I prob dont do another report cause this is Pathetik.
Just add the damn quest to your questlog and read the 2 lines of questtext. Then port to location and try it.
