### ISSUE TITLE
Titanium is not prospectable

### ISSUE THREAD

**Issue by Siabhre** [OmegaWoWeu/Decades#112]
Description:

Prospecting Titanium does not work.  When you try you get the error message "There are no gems in this". I am at 450 Jewel Crafting so it should work.  I see that this issue was submitted in January and closed out, but it is still not functioning correctly.

How to reproduce bug:

Try to prospect titanium

How it should work:

Prospecting Titanium should produce either rare or possibly epic gems, and Titanium Dust.

Screenshots:

Relevant AddOns used:
None

Source:

**Comment by blzee** [comment]
Working as intended, prospecting titanium wasnt released until 3.2
