### ISSUE TITLE
Heroic strike / Cleave Swingtimer reset when out of rage.

### ISSUE THREAD

**Issue by LoveUrk** [OmegaWoWeu/Decades#113]
Description:
Easy to check bug, Was common on Dalaran WoW for a while. Resets swingtimer if ragestarved while queueing HS/Cleave as a warrior instead of instant swinging. 

How to reproduce bug:
Basically if you're at 30 rage and Queue Heroic strike / Cleave but instead end up using a bloodthirst / Whirlwind which puts you down below 12 rage the warrior should automatically autoattack instead of trying to Cleave / Heroic Strike. It seems that it doesn't happen every time but often enough to make a big difference. 
I'd classify this as a major issue due the the already existing issue pre ToGC with rage starvation as a warrior.

How it should work:
If you queue HS / Cleave and you run out of rage it should white hit.

Screenshots:
Very hard to provide detail through a picture. 

Relevant AddOns used:
Dominos bars, Omen, Auctioneer, DBM, Recount.

Source:
Personal Testing.

**Comment by blzee** [comment]
I can’t duplicate what you’re saying, my warrior auto-attack’s just fine is dropping below ragereqs

**Comment by LoveUrk** [comment]
Had another warrior test this out aswell and he confirmed my suspicion. Try again, Spam cleave on a group of mobs while using bloodthirst / Whirlwind. When you're all out of rage and cleave is still qeueud it' supposed to automatically white hit instead of using the cleave which it isn't. So whenever we accidentaly spam too hard we miss out on mainhand auto attacks.

**Comment by ghost** [comment]
Same for druids. Easy test :

1. Build 10+ rage
2. Activate maul
3. Before maul strikes, spam swipe so you end up with 9 or less rage
4. Your maul is greyed out but still activated, however, when it's time for your bear to auto attack, it doesn't auto-attack at all, not even white-hit.

If rage is too low to execute a cleave/heroic strike/maul, your character should still white hit.

**Comment by LoveUrk** [comment]
Can imagine, it's the exact same thing with druids. Maul borrows the main hand auto attack, But when greyed out and still active it doesnt automatically White hit and cancel the queued Maul. Instead it completely resets and begins a new swingtimer. This is very very bad for rage classes. Please fix this.

**Comment by blzee** [comment]
Confirmed, it is indeed supposed to auto attack if rage falls below the value needed for an ability. Thank you for the report, forwarding to the devs.

**Comment by LoveUrk** [comment]
Thanks Blzee.

**Comment by erkondium** [comment]
i can confirm the Druid bug
