### ISSUE TITLE
PvP feral druid set (Gladiator's Sanctuary) bonus movement speed

### ISSUE THREAD

**Issue by ghost** [OmegaWoWeu/Decades#117]
**Description:**

The set gives a 15% bonus movement speed in forms while outdoors. This bonus does not reactivate when leaving an indoors area, unless the druid re-casts his form or unequips and re-equips set pieces.

**How to reproduce bug:**

1. Let a druid with the 4-set bonus run indoors in cat or bear form.
2. The bonus is deactivated, as it should : the druid has normal movement speed.
3. Let the druid run outside, the bonus is not reactivated, the druid still has normal movement speed.
4. Let the druid unequip enough set pieces to deactivate the 4-set bonus, and re-equip them. The movement speed bonus is back.

**How it should work:**

When the druid leaves any indoor area, the bonus should reactivate by itself.

**Source:**

Can't find any source. Can't find anyone anywhere mentioning this bug on retail, though. It seems like if this was blizzlike behavior, someone would've noticed and mentioned it somewhere, since it's a pretty big deal.

**Comment by blzee** [comment]
Thank you for the report, I’m looking into it. Since it is with tbc and lower armor, information on the bonus is kind of buried. I’m looking into it tho.

**Comment by ghost** [comment]
I think it's safe to assume the bonus worked exactly like the burning crusade feral swiftness, which didn't work indoors before wotlk. Only, I don't know how feral swiftness worked in tbc. Did it reactivate itself when running outside without having to recast your cat form ? (probably, imo)

Checked old wowhead comments, no mentions about having to recast cat form when running out - https://web.archive.org/web/20120619202452/http://www.wowhead.com/spell=24866#comments and https://web.archive.org/web/20120618134209/http://www.wowhead.com:80/spell=17002#comments

**Comment by blzee** [comment]
After digging & digging, it Is confirmed its supposed to automatically correct your movespeed while transitioning from outdoors to indoors without having to shapeshift. Thank you for this report!

**Comment by ghost** [comment]
Thanks. Out of curiosity, how did you confirm it ? Just want to get an idea where to look next time I'm trying to confirm a bug.
