### ISSUE TITLE
Recruit a Friend mob XP

### ISSUE THREAD

**Issue by cover25** [OmegaWoWeu/Decades#121]
Description: RAF xp doesnt work in mobs

How to reproduce bug: 

step 1. connect RAF
step 2. party
step 3. fight a mob and have one person die
step4. collect full XP
step 5. kill a mob with both party members alive and get half xp

How it should work: get full XP

Screenshots:
https://imgur.com/a/Y4uP5JU
Relevant AddOns used:
Elv ui
Source:
https://wow.gamepedia.com/Recruit-A-Friend

**Comment by blzee** [comment]
Confirmed a bug, talked to you in discord about it.
