### ISSUE TITLE
[Class] Warrior - Victory Rush not healing

### ISSUE THREAD

**Issue by Rack-man** [OmegaWoWeu/Decades#122]
Description: Warrior's ability Victory Rush is missing its healing component

How to reproduce bug: Using Victory Rush does not heal

How it should work: Victory Rush should heal the player by 20% of their full health on hit

Screenshots: N/A

Relevant AddOns used: N/A

Source: N/A

**Comment by Rack-man** [comment]
Footnote: I am uncertain whether 15% or 20% is the correct healing amount for 3.3.5a

**Comment by blzee** [comment]
It’s working as intended, the healing wasn’t implemented until patch 4.0.1(Cataclysm)
