### ISSUE TITLE
Glyph of claw doesn't work

### ISSUE THREAD

**Issue by erkondium** [OmegaWoWeu/Decades#124]
Description: claw's energy should be reduced to 30, it's still 35. I used the spells on mobs, it spends 35 energy ( i see the bar going down to 65)

How to reproduce bug:

How it should work:

Screenshots:
![image](https://user-images.githubusercontent.com/48623428/54483677-c3739f80-4857-11e9-9158-aedce49e44fd.png)

Relevant AddOns used:

Source:

**Comment by blzee** [comment]
Talent ferocity 5/5 reduces energy cost by 5, glyph reduces by another 5, equaling 35. Default rank 3 claw cost 45 energy, it’s working as intended.
