### ISSUE TITLE
Feral Spirit (Enhancement Shaman issue)

### ISSUE THREAD

**Issue by ghost** [OmegaWoWeu/Decades#127]
Description:
Feral Spirit (And other pets like Water Elemental), have their abilities on autocast everytime you summon them, despite turning off the autocast the time before. Each new summon puts back on the autocast, making the Feral Spirits (Enhancement Shaman) Leap and especially the stun, useless.
How to reproduce bug:
Summon feral spirits, turn off the stun (Bash) autocast.. dismiss feral spirits.. wait 3 minutes, summon feral spirits again and see that bash is back on autocast.
How it should work:
Turning off the Autocast for pet abilities should keep them off for each subsequent summon until manually turned back on.
Screenshots:

Relevant AddOns used:

Source:

**Comment by blzee** [comment]
Thank you for your report, confirmed a bug.
