### ISSUE TITLE
Terokk's Downfall quest object bug

### ISSUE THREAD

**Issue by Leninaomega** [OmegaWoWeu/Decades#128]
Description:
There should be a pile of bones that summons a mini boss to advance in the shatar quest line. This doesnt work. You should be able to 'talk' with the pile and then summon the boss but you are not able to interact with it.

How to reproduce bug:
Try to talk with it.

How it should work:
You should be able to talk with it giving a conversation option to summon terokk. 

Screenshots:

Relevant AddOns used:
Tried disabling all my addons but didnt work.

Source:

**Comment by MarceloTheOne** [comment]
Can't reproduce, works properly during testing, could you reopen if issue still persists?
