### ISSUE TITLE
[spell} disperse & shadowform

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#129]
Description:
Invisible Bug (untargetable) -priest only?-

How to reproduce bug:
Mount up, Use Disperse as ShadowPriest, use Shadowform.

How it should work:
After reproduction steps are done, you become completely invisible besides nameplate and untargetable until shadowform or demount.

Screenshots:
https://gyazo.com/6a892a0477892d9075f2bc1ebc19caae

Relevant AddOns used:
recount, dbm, elvui, atlasloot (none would do this i think)

Source:
ME! No[playername]!

**Comment by Xshade** [comment]
This is only a visual bug. U can still see player names/nameplate. Besides that you can target it with using any of the keybinds for targeting you have on your character.
Also this bug is from the game client rather than server stuff.
