### ISSUE TITLE
[ NPC ] : Kickin' Nass and Takin' Manes

### ISSUE THREAD

**Issue by GMShepherdOW** [OmegaWoWeu/Decades#13]
Description: NPC "Nass" has way to low HP and Armor so he dies the instant he gets in combat.

How to reproduce bug: Take the quest, spawn "Nass" and go into combat.

How it should work: Nass shouldn't die that quick.

Screenshots:  http://prntscr.com/mdrmg7

Relevant AddOns used: /

Source: https://www.wowhead.com/quest=12630/kickin-nass-and-takin-manes

**Comment by OmegaWoWeu** [comment]
As per the last comment on WoWhead, dated patch 3.0.1, Nass is actually meant to have super low HP.

Source: https://www.wowhead.com/npc=28521/nass#comments

Not a bug!
