### ISSUE TITLE
Mount problems in IF

### ISSUE THREAD

**Issue by Maltm** [OmegaWoWeu/Decades#147]
Description: I keep getting thrown off my mount in IF and other cities, as soon as there is a roof (or something else) above me it just throws me off when i try to mount up.

How to reproduce bug: mounting up in IF

How it should work: I don't get demounted instantly and can actually stay on my mount

Screenshots: can't screenshot a demount

Relevant AddOns used: None

Source:

**Comment by Deamoniakk** [comment]
If I remember correctly, on retail, that kind of "demounting" system, which is described in "how it should work" was implemented only in cataclysms 4.2 patch... Before it, whatever counted as "Indoors", like going under any type of roof that prevents you from mounting, was throwing you off the mount instantly...

**Comment by Maltm** [comment]
I'm not talking about going inside a house in the cities, i'm talking about standing in the middle of IF and getting thrown off my mount, or standing under an arch in SW.

**Comment by Bordoo** [comment]
you are using WOD Client. disable it and you will be ok.
