### ISSUE TITLE
Eye of the Storm bubble bug

### ISSUE THREAD

**Issue by sacredarrow99** [OmegaWoWeu/Decades#148]
Description:
players can go to the edge of the bubble and mount up which enables them to be half inside the bubble itself and half out of it. By jumping a few times and moving around you can get out of the bubble completely and do whatever you want before the game starts. You can go to the enemy team and wait for them or go to mid and pick up the flag immediately when it resets.
How to reproduce bug:

How it should work:
well, none of this should work how it works right now
Screenshots:

Relevant AddOns used:

Source: Sacredarrow

**Comment by alycai** [comment]
youve always been able to do that, even retail

**Comment by alycai** [comment]
> youve always been able to do that, even retail

live fix i think is more harsh start reset
