### ISSUE TITLE
Overpower Being Dodged and Parried in PvP

### ISSUE THREAD

**Issue by rreddruum** [OmegaWoWeu/Decades#150]
Description: Use overpower in PVP and it will sometimes be dodged its happend at least 5 times today in the couple of bgs that i've played so its pretty often.

How to reproduce bug: be warrior. fight something with high dodge or parry. use overpower many of times it will be dodged or parried at some point.

How it should work: overpower tooltip says that this ability can't be dodged parried or blocked.

Screenshots:

Relevant AddOns used:

Source:

**Comment by MarceloTheOne** [comment]
Can't reproduce, could you reopen the issue with additional info (screen from combat log for example) if issue still persists?
