### ISSUE TITLE
Auction house creating duplicate mail

### ISSUE THREAD

**Issue by areus1** [OmegaWoWeu/Decades#157]
Description: Whenever someone buys something from me on the auction house, I get two pieces of mail. One with the actual gold and another that says the auction is still pending. This is annoying because after a while your mail will fill up if you post a lot of auctions, making you unable to send your bank alt mail from your main because of the error message "You have reached the in game cap of mail recipients".

How to reproduce bug: Sell something on the auction house

How it should work: Only 1 mail is sent when the item is purchased notifying the seller it's been purchased, then after 1 hour the mail allows the gold to be taken.

Screenshots: https://i.imgur.com/MCASiI8.png

Relevant AddOns used:

Source:

**Comment by Bordoo** [comment]
the auction house is working as intended you can see more information about it on http://www.worldofwarcraft.com/patchnotes/patch2p10.html
