### ISSUE TITLE
Set Bonus not working.

### ISSUE THREAD

**Issue by sambojuice** [OmegaWoWeu/Decades#159]
Description: Set bonus donesnt work after TMOG.

How to reproduce bug:

How it should work:

Screenshots: http://tinypic.com/r/ifagky/9

Relevant AddOns used:

Source:

**Comment by chernobylzyo** [comment]
This is not a bug. The set bonuses are working despite it not being shown in the character hub. Took me legit 1 minute to test this on 5 characters and its working on every single one. Maybe try actually using the set-bonus. Of course its not shown as 4/5 set when the mogged item overwrites the current one.
