### ISSUE TITLE
The Battle for undercity

### ISSUE THREAD

**Issue by Aelior** [OmegaWoWeu/Decades#161]
Description: I am trying to do the battle for undercity but Thrall isn't on the spot so I can talk to him and start the event.  Sylvanas and vol'jin are standing there but thrall isn't 

And also the problem is that even if I abandon the quest I am still phased when I visit oggrimar can u plz help me

How to reproduce bug:

How it should work:

Screenshots:
![image](https://user-images.githubusercontent.com/48823421/55943140-ab245400-5c4e-11e9-94ce-ae878dca0416.png)

Relevant AddOns used:

Source:

**Comment by Bordoo** [comment]
someone already started the quest .you need to wait till thrall returns.
