### ISSUE TITLE
Enhancement Shaman spell miss issue.

### ISSUE THREAD

**Issue by ghost** [OmegaWoWeu/Decades#165]
Description:
Random spell misses in raids / dungeons despite being spell hit capped.
Tested with 22% Spell Hit (5% over cap), + 6% from talents, + 3% from Shadow Priest for a total of 31% hit, 14% over the spell cap.... Still got spell misses on some bosses for seemingly no reason.
How to reproduce bug:
No idea, it just seems to randomly happen during raids, sometimes not at all, sometimes extremely often.
How it should work:
Hit cap is called hit cap for a reason.
Screenshots:
None.
Relevant AddOns used:

Source:

**Comment by Monziltinks** [comment]
I thought I'd add my part to this report: 
The Dual Wield Specialization does not affect spell hit. 
An enhancement shaman needs 17% spellhit (14% from gear, 3% from shadow priests/boomkins).

Unfortunately I do not have a level 80 shaman so I am unable to test it for sure, but if you go to a Heroic Training Dummy, use double Flametongue Weapon you can easily check the amount of misses you get with Flametongue Weapon with various levels of spell hit rating.
I suggest testing 1000+ hits with 0 hit rating and another 1000 hits with 17% spell hit to find out if there's a problem, and if there is a problem, how severe it is.

**Comment by ghost** [comment]
You sound like Undertower from our guild, unfortunately though you're wrong.
The Dual Wield Specialisation talent DOES effect spell hit rating. There are multiple examples of things in game effecting only 1 (Spell or hit), and they're worded as such.. For example, Virulence, the Death Knight talent. 
Again, the frost death knight talent Nerves of Cold Steel (Increases your chance to hit with one-handed melee weapons)..

The Word>>>>hit<<<< covers both bases. When it doesn't, it is specifically worded that way in the talent or ability.


Please research before you post misinformation.

**Comment by ghost** [comment]
For example, here is a visual reference to show that when it is meant for only one aspect, Blizzard words it that way.

https://imgur.com/a/vR58QAY

when it is just the word "hit", it applies to both, just like the gems and enchants do.

**Comment by Monziltinks** [comment]
You're free to believe whatever you want, but if you check the retail sims, guides and comments they all agree it doesn't affect spell hit.

Here's a post from 11/20/08, 12:36 PM:
https://web.archive.org/web/20100308024704/http://elitistjerks.com/f79/t52324-shaman_simple_questions_simple_answers/#post982040
Here's a screenshot of Rawr without talent:
https://gyazo.com/5fba5284c34ad751a98f27061a3e04c0

And another screenshot with the talent:
https://gyazo.com/aa34211015d2e8ba1cf6e237f12464aa

**Comment by ghost** [comment]
So, your argument against the BLIZZARD WRITTEN TALENTS is to post custom made, none blizzard related simulation content? Seriously?

Sounds legit, i'm glad we cleared this up. Kappa

**Comment by Monziltinks** [comment]
https://www.wowhead.com/forums&topic=79147
https://us.battle.net/forums/en/wow/topic/2228175457
https://www.mmo-champion.com/threads/622605-Dual-wield-specialization
https://web.archive.org/web/20100722020047/https://www.wowhead.com/spell=30819

This last one is barely legible but this is what wowhead has to say about the talent in July 22, 2010:
"Effect | Apply Aura: Mod Melee & Ranged Hit Chance %Value: 6"

**Comment by ghost** [comment]
Again, your arguement against BLIZZARDS OWN WORDING which is consistent across the entirity of the game, in every single talent tree for every single class, is posting something written by tinfoilhatman from an article you found on google?

Solid argument there, Undertower. Once again, Blizzard created the game, they worded their talents SPECIFICALLY for every single class and spec in game that when something is meant for only one thing, it CLEARLY states that.

This talent has been working for spells AND melee hit since it's inception in TBC. It worked for spells on TBC retail, on every TBC private server thereafter. It worked for spells in retail WOTLK, and on every WOTLK server thereafter.

This is the ONLY PLACE where it doesn't work for spells, and according to you, this is the ONLY PLACE including retail, that has it right? Do you realise how much of an absolute tool you sound?


No more replies, this guy is a sourpuss, nothing more.

**Comment by Monziltinks** [comment]
I post my sources and let the devs decide.

**Comment by ghost** [comment]
Your "sources" are independent none confirmed typings by randomers.

Mine are from Blizzard.

There isn't even an argument here.
