### ISSUE TITLE
Stuck in Battle for undercity phasing

### ISSUE THREAD

**Issue by wcked** [OmegaWoWeu/Decades#167]
Description: Im stuck in the battle for undercity phasing, my client crashed as i completed the wrathgate never got the quest for undercity, walked there myself did the battle, didnt get tp'd out like your suppose to, hearthed to org, no vendors, no mobs spawning in durotar etc.

How to reproduce bug: Crash as the wrathgate strts

How it should work: After completing the battle for undercity I should of phased back into normal wow.

Screenshots:

Relevant AddOns used:

Source:

**Comment by NathanNatNat** [comment]
You need to do the actual quest, not just the battle by its self....  you need to go back to the wrath gate and get the quest from Alexstrasza, she will be near the entrance that the LK comes out of at the top of the stairs.

**Comment by Bordoo** [comment]
> You need to do the actual quest, not just the battle by its self.... you need to go back to the wrath gate and get the quest from Alexstrasza, she will be near the entrance that the LK comes out of at the top of the stairs.

thank you. that is right.
