### ISSUE TITLE
Standard Pet Attack isn't affected by Pet Happiness/Unhappines

### ISSUE THREAD

**Issue by Monziltinks** [OmegaWoWeu/Decades#171]
Description:
The Standard Pet Attack(Bite, Claw, Smack) of pets does not get the bonus nor the malus from having happiness or unhappiness.

How to reproduce bug:
Attack a target with a Happy(125% damage), Content(100% damage) or Unhappy pet(75% damage).
Compare the damage of the Standard Pet Attack(Bite, Claw, Smack) with the different happiness levels.

How it should work:
The damage of the Standard Pet Attack(Bite, Claw, Smack) should change depending on Pet Happiness.

Screenshots:
As you can see below, the damage of Bite remains the same no matter the happiness, while the damage of the melee swing is affected.

![Pet bite full happiness](https://user-images.githubusercontent.com/19599710/56507208-e06b5480-6520-11e9-9e26-ca3e951289f6.jpg)
![Pet melee full happiness](https://user-images.githubusercontent.com/19599710/56507222-e5c89f00-6520-11e9-87e7-c8c9b4df22d8.jpg)
![Pet bite unappy](https://user-images.githubusercontent.com/19599710/56507229-e82af900-6520-11e9-91a6-e1be032bf92b.jpg)
![pet melee unhappy](https://user-images.githubusercontent.com/19599710/56507232-e9f4bc80-6520-11e9-95e7-1559d8977816.jpg)

Relevant AddOns used: Shadowed Unit Frames, Recount

Source:
The Tooltip
http://web.archive.org/web/20100309104954/http://www.wow-petopia.com/html/guides/feeding.php

**Comment by JonasD92** [comment]
So when the pet is unhappy its melee attack hits for avg 127, and when its unhappy, it hits for avg 213. The normal damage(100%) should be around 170. 
Unhappy damage should be: 170 * 0,75 = 127,5. 
Happy damage should be: 170 * 1,25 = 212,5.
So you proved yourself with your screenshots that the standard pet attack is affected by happiness.
