### ISSUE TITLE
Alchemy recipe: [Elixir of Major Defense] The NPC doesn't sell the recipe.

### ISSUE THREAD

**Issue by danielszkaliczki** [OmegaWoWeu/Decades#175]
Description:
To complete the "Master of Elixirs" quest for alchemy you have to make 3 type of Elixirs, one of them is the "Elixir of Major Defense" which recipe you could buy from Daga Ramba in Thunderlord Stronghold, but the NCP doesn't sell the item. 

How to reproduce bug: I've been sitting there for 3 hours waiting for the recipe. I've been there multiple time in the last 3 days but never seen the recipe (you can't find it even in the auction house, nether the recipe and the Elixir).

**Comment by OmegaWoWeu** [comment]
This is not a bug. The item is there but it's restock time is set to 12 hours.
-Bliss
