### ISSUE TITLE
Master looter Discontected all loot lost !

### ISSUE THREAD

**Issue by yogtzel** [OmegaWoWeu/Decades#176]
Description:We were running a Voa 25 man . In the middle of the fight the raid leader ,also the master looter went afk ! After the boss died we waiting for him to come back thing that never happened because minutes later he disconected from the game ! Me and some other raid members were waiting for his return... after some minutes i oponed a ticket to talk to a GM because we couldnt take the loot ! we were  waiting a good amount of time When game warning told us dungeon was going to Reset in 30 minutes because wintergrasp was about to start ! 30 more minutes in the dungeon , leader still disconect , the game Didnt change leader for our raid ! we were waiting more or less 1hour leader still the same.. Loot still master loot! GM didnt anwser to My ticket ! WINTERGRAPS started we all got teleport out LOOT Was Lost for ever ?

How to reproduce bug:

How it should work: EASY , game should have change raid leader after some minutes of his disconect ! i want My loot ! HOW i am supposed to get it now ?? is a way to get it , As it was my class and my spec and the only raid member who needed that !? WHY should i lose LOOT for another person problem ?

Screenshots:

![](https://cdn.discordapp.com/attachments/329230371323510784/570263756395773982/unknown.png)

Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
Issue tracker is a place for bug reports. To report an abuse contact our staff on discord.
