### ISSUE TITLE
Random dungeon finder lockout

### ISSUE THREAD

**Issue by zyanowow** [OmegaWoWeu/Decades#178]
Description:
After being saved to all instances you should still be able to queue using the RDF tool.

How to reproduce bug:
Being saved to all instances makes it impossible to queue for random dungeon.

How it should work:
You were able to queue even if saved to all dungeons as of 3.3

Screenshots:

[RDF response when trying to queue](https://imgur.com/a/vjgBfWI)
[List of saved instances 1](https://imgur.com/a/ILFbZ5h)
[List of saved instances 2](https://imgur.com/a/UZyrvxm)

Relevant AddOns used:
N/A

Source:
Discussion from the sunwell-community. Sources linked in the post.
https://sunwell-community.com/index.php?/topic/372-que-for-random-hc-dungeon-not-possible-if-saved/

[Direct link to endgated](https://www.engadget.com/2009/12/08/patch-3-3-the-dungeon-finder-guide-page-2/?guccounter=1&guce_referrer_us=aHR0cHM6Ly9zdW53ZWxsLWNvbW11bml0eS5jb20vaW5kZXgucGhwPy90b3BpYy8zNzItcXVlLWZvci1yYW5kb20taGMtZHVuZ2Vvbi1ub3QtcG9zc2libGUtaWYtc2F2ZWQv&guce_referrer_cs=kjONFKh8BBbyj91MMCi8FQ)

**Comment by Bordoo** [comment]
![FG2huxt](https://user-images.githubusercontent.com/47177389/57349893-26572800-7171-11e9-903b-dea0a482b915.png)
you can do each heroic dungeon once per day. change this to normal mod and you will be good to go.
