### ISSUE TITLE
Quest Battling The Elements is uncompletable

### ISSUE THREAD

**Issue by Raiven696** [OmegaWoWeu/Decades#179]
Description: After accepting the quest the Seething Revenant's dont give quest credit, also if you attack them near the Frost Giant Stormherald's the Giants will aggro to you, they dont do any dmg but you have threat on them. Also the quest requires 10 kills and there are only 5 spawns.

How to reproduce bug:

How it should work: Giants don't aggro, Mob's give credit

Screenshots:

Relevant AddOns used:

Source:

**Comment by Bordoo** [comment]
you have to mount the giant standing right next to the quest giver.Snorri is the 80 elite next to the king. You mount him and walk to a snow bump, pick it up, tab until you get a seething remnant, then throw the snowball.
 we tested this quest and it was working properly
