### ISSUE TITLE
Looting Error

### ISSUE THREAD

**Issue by genetik37** [OmegaWoWeu/Decades#180]
Description:
This isnt much of a bug, but the great CS told me to put this here.
How to reproduce bug:
Kill final boss in heroic oculus. needed and won the staff of draconic command. Didnt receive the item. 
How it should work:
Kill final boss in heroic oculus. needed and won the staff of draconic command. receive the item. 
Screenshots:
![WoWScrnShot_042719_144953](https://user-images.githubusercontent.com/50057828/56854387-cf955700-6903-11e9-971a-3c5e5df7794e.jpg)
Relevant AddOns used:

Source:

**Comment by Xshade** [comment]
You won 2 items if you look close. Also if u had 1 free slot for both weapons (you could have sold a trash item to look like its bug or you maybe realised that you had full inventory for for the staff and u got your self free slot for the screenshot) its obvious that you cant recieve both items. Secondly this pick doesnt prove anything bcuz you could sold the staff before you make the sceenshot or put it in bank or something. 

Idk if this could be bug or player mistake
