### ISSUE TITLE
[Quest] Finding the Phylactery 

### ISSUE THREAD

**Issue by Zero9519** [OmegaWoWeu/Decades#184]
Description: In Dragonblight there is a quest named above that allows you to ride a mount into a location and click an item. Item does not exist and instead just cancels out.

How to reproduce bug: click the item.

How it should work: you get an item for the quest.

Screenshots:

Relevant AddOns used:

Source:

**Comment by Bordoo** [comment]
![quest test](https://user-images.githubusercontent.com/47177389/57349013-b5624100-716d-11e9-9719-2274829284c1.PNG)
we tested it and it is working properly
