### ISSUE TITLE
(quest) Escape from Durnholde

### ISSUE THREAD

**Issue by madafka** [OmegaWoWeu/Decades#186]
Description: This chain quest, starts by "To the master's Lair" is a caverns of time chain quest, that allows you to enter Black Morras dungeon, i start the chain quest but in the quest "Escape from Durnholde, especify located in old hillsbrad, you talk to thrall to initate, after that you have to release him from jail by talking him again, but when you talk him he dosn't give you the option to start the quest.

**Comment by Bordoo** [comment]
We checked it it was working properly.
In the Caverns of Time, you can do the Durnholde instance. When you enter the instance, talk to the humanoid Erozion, he will give you these Incendiary Bombs. If for any reason you lose them, go back to him and get more.
Each one of the buildings in the pit at Durnholde has a darker-brown barrel. Place one Incendiary Bomb on each. You will need to kill the guards to do this.
The fires they cause will call Lieutenant Drake. **you need to kill him.**
Then go into the basement of the hold. The basement entrance is under the stairs up.
Free Thrall, and as you leave the gate Captain Skarloc will appear. 
You must speak, right click, Thrall to get him to move out of the basement, and again to get him to leave Durnholde for Tarren Mill. Taretha is upstairs in the Inn, which you will reach after Thrall searches the barn, and the church. You must kill the mobs to get Thrall to move on. Click on Thrall to get to the next segment after he finds Taretha.
