### ISSUE TITLE
Shadow Priest Mind Flay into Instant Dot GCD issue

### ISSUE THREAD

**Issue by Zero9519** [OmegaWoWeu/Decades#188]
Description: Currently when channeling mindflay if you clip the channel you will not incur a GCD cooldown on your action bars if you have clipped it with an instant Dot such as Devouring Plague or SWP, SWD also. 

How to reproduce bug: Press mind flay and clip it with an instant cast spell.

How it should work: a GCD is displayed and cooldown incurred, along with a character movement displaying a spell being cast

Screenshots: https://imgur.com/a/tyjFCqt (notice SWP has been applied, character has no movement, and bars have no GCD on them).

Relevant AddOns used: ELVUI, WA2, Key Presser, Recount. I have tried with and without addons and the issue still presents itself.

Source:

**Comment by Xshade** [comment]
Are you joking or what? Also do you know what your talents are doing? Have you read the description of this [talent](https://db.omegawow.eu/?spell=47582) ?
https://youtu.be/BsKgb0pxqdc

**Comment by MarceloTheOne** [comment]
Can't reproduce, GCD is applied correctly every time for me.
