### ISSUE TITLE
Alchemy: Epic Transmute Recipes Missing

### ISSUE THREAD

**Issue by BroomBred** [OmegaWoWeu/Decades#197]
Description: 
The following Alchemy Recipes should be trainable at skillevel 450, but they aren't.
Transmute: Majestic Zircon
Transmute: Eye of Zul
Transmute: Ametrine
Transmute: Dreadstone
Transmute: King's Amber
They were visible while the skill was below 450 but vanished as soon as Alchemy hit 450. This bug was known in retail aswell.

Screenshot at trainer, showing that it is not trainable: https://gyazo.com/a9b94a3d530fe7352d7d78d66c2766c2

Comments from Wowhead with people experiencing the same problem:
https://www.wowhead.com/quest=14151/cardinal-ruby#comments:id=1145147
https://www.wowhead.com/quest=14151/cardinal-ruby#comments:id=1160212

It would be great, if you could grant this recipes to my shaman "Shamful", because not everyone is experiencing this bug and the lack of important transmutes is quite annoying.

Relevant AddOns used:
None. Tried to disable all addons and check for the recipes, but they were still unavailable.

**Comment by Genjim** [comment]
Having the same issue, got the message I should try it here. Did it get resolved for you?

**Comment by MarceloTheOne** [comment]
Epic Gem transmutes will be added in 3.2 patch (currently we're on 3.1).
