### ISSUE TITLE
Issue with RDF when YOU leave party

### ISSUE THREAD

**Issue by sicknot1** [OmegaWoWeu/Decades#2]
Description: Leave rdf, and instead of instantly teleported to your original location, you get the message (screenshot) and if you leave by the entrance, you find yourself on the other side of it. In my case on the caverns in the barrens that lead to WC

How to reproduce bug:
que rdf, right click your icon, leave party

How it should work:
You get TPed to your orig location

Screenshots:
![wowscrnshot_012619_212607](https://user-images.githubusercontent.com/35937937/51794529-63e00880-21b3-11e9-9255-95f88b900a97.jpg)

Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
We were unable to reproduce the issue.
