### ISSUE TITLE
Battle For undercity 

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#20]
Description: its is buggy in both sides ...in allies i belive it  is disabled for now and for hordes it get auto compelete but there is no one to turn in .this results players stuck in a wrong phase which they cant get out . even after going to dalaran and coming back to stormwind they stuck in that wrong phase again somehow.

**Comment by OmegaWoWeu** [comment]
It is not bugged. The quest has been tested after this report has been made, and it's not bugged.

It's a rather unconventional quest in that it takes a while for things to start.

On Alliance, for example, you need to idle around Varian for about 5 minutes before he starts charging into Undercity. There are 1-2 extra phases such as this where it seems the quest gets stuck, but it's all part of how the quest actually works.

The Horde version was disabled for a while, but will be re-enabled tomorrow.

Not a bug!
