### ISSUE TITLE
Making Peace

### ISSUE THREAD

**Issue by Apokaliptika** [OmegaWoWeu/Decades#201]
Description: Start the quest, speak with the target NPC that kicks you, When you try to finish the quest from the same NPC that you got the quest, you cannot, you will attack him. The NPC is green (friendly) but you can attack him.

How to reproduce bug: Start the quest, speak with the target NPC that kicks you, When you try to finish the quest from the same NPC that you got the quest,you cannot, you will attack him. 

How it should work: Speak with friendly NPC and finish the quest normally.

Screenshots: http://prntscr.com/ntnisf AND http://prntscr.com/ntnivo 

Relevant AddOns used: None

Source: In-game.

**Comment by Apokaliptika** [comment]
The quest is : Making Peace https://www.wowhead.com/quest=12573/making-peace

**Comment by MarceloTheOne** [comment]
Can't reproduce it, works correctly for me, could you reopen issue with more info if issue still persists?
