### ISSUE TITLE
Paladin - Benediction doesn't Reduce the Mana Cost of instant spells

### ISSUE THREAD

**Issue by Jannis95** [OmegaWoWeu/Decades#204]
Description:
5/5 Points into Benediction - Retribution Talent tree - should reduce the mana cost of all instant cast spells by 10%. But it doesn't reduce the cost by any amount.

How to reproduce bug:
Use the spell and look at the mana used.

How it should work:
It should reduce the mana cost of instant cast spell by 10%.

Screenshots:
Examples: Crusader Strike
![WoWScrnShot_053019_130805](https://user-images.githubusercontent.com/46106658/58629418-bdc91a00-82dc-11e9-8b0a-cc0ef80d60fe.jpg)
![WoWScrnShot_053019_130830](https://user-images.githubusercontent.com/46106658/58629617-4051d980-82dd-11e9-9a21-69796e0ecd73.jpg)
Divine Storm:
![WoWScrnShot_053019_130845](https://user-images.githubusercontent.com/46106658/58629627-4a73d800-82dd-11e9-8046-84549c168d53.jpg)
![WoWScrnShot_053019_130906](https://user-images.githubusercontent.com/46106658/58629645-52cc1300-82dd-11e9-9865-7ca3ae7aeb97.jpg)
Exorcism on Art of War proc:
![WoWScrnShot_053019_131158](https://user-images.githubusercontent.com/46106658/58629668-65464c80-82dd-11e9-9d09-2f0283def1ba.jpg)
![WoWScrnShot_053019_131215](https://user-images.githubusercontent.com/46106658/58629696-742cff00-82dd-11e9-8f29-b93c8eb756db.jpg)
![WoWScrnShot_053019_131254](https://user-images.githubusercontent.com/46106658/58629715-827b1b00-82dd-11e9-9212-2133eedb675b.jpg)

Relevant AddOns used:

XPerl - UI

Source:

**Comment by ih8mondays** [comment]
You need to find some source to back this up with because you might be right, but here are some reasons you might be wrong.
Exorcism isn't an instant spell even if you reduce it to be instant cast and while Blizzard™ generally have super akwardly worded spell and talent text i think it's a stretch to assume it should be affected.
Now i'm not 100% sure about this next part, but i recall Crusader Strike and Divine storm as not being classified as spells which would explain why it doesn't reduce their mana cost.
I know i'm raining on your parade, but i only hope to improve your bug report.

**Comment by Jannis95** [comment]
Here you can see all the spells that get Modified by the talent: https://wotlk.evowow.com/?spell=20105
Exorcism is also part of it and so is Hand of Light -> but should only reduce the mana if it's by an Art of War proc.
I tested it with using Buffs. They also don't get reduced by 10% of their Mana Cost.
https://wow.gamepedia.com/Hand_of_Reckoning
-> Patch 3.1.0. Hand of Reckoning also gets affected by Benediciton which is an other Instant Cast spell.
![WoWScrnShot_053019_175220](https://user-images.githubusercontent.com/46106658/58645939-9ab26080-8304-11e9-90f7-7361e5853f57.jpg)
![WoWScrnShot_053019_175255](https://user-images.githubusercontent.com/46106658/58645945-9dad5100-8304-11e9-90f2-8625320adf51.jpg)

Crusader Strike and Divine Storm are classified as Spells:
https://www.wowhead.com/spell=132331/crusader-strike
https://www.wowhead.com/spell=228256/divine-storm

Info about Benediction in general:
Affected Spells:
The first 5 points a Retribution Paladin generally spent were in this talent, as all of a Paladin's outgoing attacks are instant casts; Judgments, Exorcism, Divine Storm, Crusader Strike, Consecration, Hammer of Justice, Hammer of Wrath, Repentance. This was of huge benefit for long running fights.

https://wow.gamepedia.com/Benediction_(paladin_talent)

On the right you can't see Divine Strom listed on the Affected Properties, but that doesnt make any sense, as Divine Strom is no different to Crusader Strike. And some DB's are missing on Information which is why I sent you several links.

**Comment by ih8mondays** [comment]
I must say this looks way more convincing. On a side note you should add your links under your sources. :D

**Comment by Jannis95** [comment]
Will do for future references. Sorry for that! :)

**Comment by ih8mondays** [comment]
So you've been right so far, but could you post a picture of the mana cost of the spells with and without "Benediction" talented?

**Comment by MarceloTheOne** [comment]
Can't confirm, all listed spells have reduced mana costs.
