### ISSUE TITLE
Reconnaissance Flight

### ISSUE THREAD

**Issue by Captainweed** [OmegaWoWeu/Decades#205]
Description: While you're on the plane, it is meant for the plane to get hit and you should have to get it back to a landing pad where you got the quest. Though right now it is impossible as the plane loses all its speed and you can't get there before the plane explodes.

How to reproduce bug: Make the quest

How it should work: The plane should go way faster so that you can go back to the landing pad.

Screenshots:

Relevant AddOns used:

Source:

**Comment by MarceloTheOne** [comment]
pressing space after taking control of the plane fixes the problem
