### ISSUE TITLE
No Epic Gem Transmutes recipes from Alchemy Trainer in Dalaran

### ISSUE THREAD

**Issue by Genjim** [OmegaWoWeu/Decades#215]
Description: I'm a new player so I asked via a ticket if this was a problem or not (or even in the game) but I only got the response to submit it via here. I got the Cardinal Ruby quest but the Alchemy trainer doesn't sell my Epic Gem Transmute recipes (which it should via the Wikis etc that I've consulted), so I basically can not finish this quest. I learned that in retail this was a bug as well for a lot of people so I wondered, are epic gem transmutes even in the game or am I bugged? Character name is Elfriede.

How to reproduce bug:

How it should work: I should be able to get the recipes from Linzy Blackbolt according to the Wikis.

Screenshots:
![WoWScrnShot_060719_133058](https://user-images.githubusercontent.com/51480383/59101208-884dad80-8928-11e9-8bd0-bb11f6bd4b73.jpg)

Relevant AddOns used: Elvui, Npcscan, Gatherer

Source:

**Comment by MarceloTheOne** [comment]
Epic Gem transmutes will be added in 3.2 patch (currently we're on 3.1).
