### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Smilkey** [OmegaWoWeu/Decades#216]
Description:
The quest "Flight of the Wintergarde Defender" is not working properly. You can accept the quest, but it all stops when you mount the gryphin. It just stays on the ground and the character is unable to do anything at all. The only way to dismount (as far as I know) is to exit the game.

How to reproduce bug:

How it should work:
The gryphin is suppose to start flying over a certain area. 

Screenshots:
![WoWScrnShot_060719_133730](https://user-images.githubusercontent.com/51481412/59103417-13ca3d00-892f-11e9-87b8-864781c76f4e.jpg)

Relevant AddOns used:

Source:

**Comment by MarceloTheOne** [comment]
You are supposed to use 'Wintergarde Gryphon Whistle' to ride the gryphon.
