### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by darkon83** [OmegaWoWeu/Decades#220]
Description:the quest "the force of neltharaku" is bugged(the chain quest in outlands that alows you to get a netherdrake). also the npc dragon neltharaku himself that gives the chain quests sometimes is bugged and disapears

How to reproduce bug: the quest item "enchanted nethervine crystal" in this quest doesnt works

How it should work:you suppose to use this item on the dragon riders in the dragonmaw fortress and seperate them from their dragons.then kill the riders and the dragon is free and so you complete the quest.

Screenshots:
![image](https://user-images.githubusercontent.com/51678445/59222251-ad435a00-8b8e-11e9-81e7-d619be41a789.png)
![image](https://user-images.githubusercontent.com/51678445/59222292-c51ade00-8b8e-11e9-8b7c-ab1e20576067.png)

Relevant AddOns used:

Source:since you are going to fix this bug please check ALL the rest chain quests there for the dragon quest because it seems there are all buged.and you are free to send me a gift for my help to you :P :)

**Comment by MarceloTheOne** [comment]
Can't reproduce, got quest credit after using quest item.
