### ISSUE TITLE
Orb of the Sin'dorei/ Shaman interaction

### ISSUE THREAD

**Issue by buckfalkans** [OmegaWoWeu/Decades#223]
Description: When you use the orb, you cant BL due to lvl restriction. Because it drops in a lvl 70 instance, I'd assume the server sees ur char as lv70 when you morph in a belf, but that obviously shouldnt be the case and BL should be useable while morphed.

How to reproduce bug: Go do MT, get the orb and try to do bl

How it should work: -

Screenshots: -

Relevant AddOns used: -

Source: -

**Comment by MarceloTheOne** [comment]
Can't reproduce, could you give some more info regarding this issue?

**Comment by buckfalkans** [comment]
I got the orb from MT today and I cant do BL while being mogged in a belf because level restriction, aka because its from TBC the orb mogs me in a lvl 70 shaman so I cant do the lvl 80 bloodlust.

**Comment by MarceloTheOne** [comment]
Still can't reproduce it, give me a screenshot or something.

**Comment by buckfalkans** [comment]
Okay rip its fine now, idk what the issue was
