### ISSUE TITLE
Death grip Minimum range bug

### ISSUE THREAD

**Issue by Kevin-Michielsen** [OmegaWoWeu/Decades#225]
Description: If i'm right on top of an other person, or close buy i can't use death grip. Death grip has NO minimum range that you have to be removed of the target. DK basicly loses an interrupt option for pvp.

How to reproduce bug: Stand on top of an enemy and try to use the spell Death grip. it will give the error message target too close

How it should work:  You should be able to use death grip from anywhere, as long as the target isn't OUT of range.

Screenshots: https://imgur.com/a/xElQvc6

Relevant AddOns used: /

Source: None of the sources mentions anything of this 'Too Close'
https://wotlk.evowow.com/?spell=49576
https://www.wowhead.com/spell=49576/death-grip
https://wowwiki.fandom.com/wiki/Death_Grip

**Comment by MarceloTheOne** [comment]
Any proof that minimum pvp range for death grip shouldn't exist?

**Comment by Kevin-Michielsen** [comment]
http://forum.warmane.com/showthread.php?t=331954

**Comment by Kevin-Michielsen** [comment]
Read somewhere in the middle of the topic I linked.
