### ISSUE TITLE
[ ITEM ] : The Egg of mortal Essence

### ISSUE THREAD

**Issue by GMShepherdOW** [OmegaWoWeu/Decades#23]
Description:  Your direct healing and heal over time spells have a chance to increase your haste by 140 for 10 sec when you equip this item, altho on WARLOCKS it should be triggered by [Death coil] and [Drain life]  spells

How to reproduce bug: Make a level 80 warlock, equip the trinket and use death coil of drain life

How it should work: it should proc haste from trinket

Screenshots:

Relevant AddOns used:

Source: wowhead/wowwiki

**Comment by OmegaWoWeu** [comment]
WoWHead comment that states it can't proc from these abilities: https://www.wowhead.com/item=40685/the-egg-of-mortal-essence#comments:id=638822

It also mentions it can proc from Life Tap, but more recent comments (3.1+) state Life Tap has been removed from the "proc pool", so it won't proc from that either.
