### ISSUE TITLE
[ARENA] Combat Bug for Pet Classes

### ISSUE THREAD

**Issue by mecces** [OmegaWoWeu/Decades#239]
Description: I am not able to sap Pet classes like Warlock, Hunter or DK even tho they are not infight and i am in stealth mode

How to reproduce bug: 

How it should work: DKs for example just send the pet offensively on my priest and from that moment on as he sent the pet he is infight which he should only be when the pet reaches my priest and not before. With other Pet classes it is the same problem

Screenshots:

Relevant AddOns used:

Source:

**Comment by Bellzubab** [comment]
Do you happen to have any kind of source for this?

http://www.arenajunkies.com/topic/118924-combat-bug-with-pet/ implies that this is how it worked on retail
