### ISSUE TITLE
[ NPC ] Bristleback thornweaver

### ISSUE THREAD

**Issue by GMShepherdOW** [OmegaWoWeu/Decades#24]
Description: The npc keeps getting stuck in the tree.

How to reproduce bug: teleport to the creature and watch him get stuck in the tree

How it should work: shouldn't be stuck in the tree

Screenshots: http://prntscr.com/mfdfik & .npc info http://prntscr.com/mfdgrh
 
Relevant AddOns used:

Source: omegawow live server

**Comment by OmegaWoWeu** [comment]
Confirmed.

He keeps coming in & out of the tree.

Entry: 3261
GUID: 20208
Position: -1876 -1985 92 (at the time of .npc info pinging)

Suggested fix: Move spawn point lower on the X axis by 5-10 degrees.
