### ISSUE TITLE
"Warrior beserker  stance quest giver  "

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#25]
Description:Hi dear GM

I have a problem with the quest for the berserker stance for the Warrior.
I stand on the isle where the quest is and the icon over the head of Klannoc Macleod shows that a quest is available.
when i talk to him then there is no quest and he only says "greetings". i´ve made the prequest, tried it with deleting the wtf and wtb. 
I dont have Addons usw.

Alex

How it should work:
the quest giver suppose to give the quest 

source : player

**Comment by sicknot1** [comment]
I got the whole chain completed a couple of days ago
You mean the ISLANDER quest or the one with the fray? 
Did a GM resolved your issue ingame?

**Comment by OmegaWoWeu** [comment]
Seems to work for me. Could you confirm it is still bugged for you? Post pictures of the "Greetings" gossip text if yes.
