### ISSUE TITLE
Onyxia Incorrect Loot!

### ISSUE THREAD

**Issue by phantom1004** [OmegaWoWeu/Decades#253]
Description: Since the introduction of Onyxia 10m and 25m the boss is incorrectly dropping the wrong Emblems, it should drop Triumph, but instead is dropping Conquest
How to reproduce bug: Kill The boss?

How it should work: Should drop 3x Triumph for 10 and 25 man kills

Screenshots: I wont paste screenshots from the server because you can easly look it up yourself, but see "Source" for 2 links to 10m and 25m videos from Retail Release

Relevant AddOns used:

Source:
http://prntscr.com/olmx69 (Patch release date September 22nd 2009)
https://www.youtube.com/watch?v=G2yc_Uw89vQ (10m kill showing Triumph drops)
https://youtu.be/27k7dLkAjvc (25m kill showing Triumph drops)
Please check the dates of them videos! that is proof enough

**Comment by Absolution2015** [comment]
UPDATE `loot_template` SET `item` = 47241 WHERE `item` = 45624 AND `entry` = 10184;

That _should_ fix it, changing EOCs to EOTs for Onyxia. The only weird thing is, generally bosses have one separate creature ID for both difficulties, yet Onyxia only has one in the DB. If she's just wired to work that way, then this fix should do the trick. If there's something more sinister afoot, then it might only fix the 10-man loot (I could only find one ID on the online Omega DB, usually they have extra IDs but they're only shown in the DB fields).

If she has a difficulty_entry1 ID, then it can be easily inserted into the above fix.

Cheers,
Nox.

**Comment by Absolution2015** [comment]
Ony25 still drops conquest. It needs the extra ID, like I described in my paragraph above.

**Comment by MarceloTheOne** [comment]
Looks fine in database, you probably checked before update
