### ISSUE TITLE
Swimming in air and getting flagged as cheater by Anticheat at Outlands

### ISSUE THREAD

**Issue by Smuganimegrl** [OmegaWoWeu/Decades#255]
Description:
I managed to make my state go to swimming and combat didnt remove it at netherstorm where there is practically no water.

How to reproduce bug: 

I was doing a quest Measuring Warp Energies in Netherstorm. In the quest you go and use item called Warp-Attuned Orb near the 4 pipes that surround Manaforge B¨naar. I used the item, mounted and apparently gained altitude too fast. It dismounted me and I gained swimming state. I called in to a gm on discord and Aegean answered the call. He had apparently been stalking me pretty much from the moment when I gained the swimming state. Apparently anticheat automatically flagged me as a cheater.

I showed him the place where it happened and managed to recreate it 3 more times for him. We didnt test out the other pipes but the one that is in screenshot.

How it should work:

Under no circuimstances i should be able to get swimming state on dry land

Screenshots: 

https://imgur.com/IfaROsm
https://imgur.com/WrZmDPD

Relevant AddOns used: Addons are not relevant to this

Additional Notes:

We didnt test it on the other pipes if its possible to recreate

Effect persisted on gm teleport at outlands but didnt keep the state of swimming when we entered Mechanar

Effect didnt persist when Aegean ported me to Dalaran

We didnt test warlock summon or other means to "fast travel" (Hs for example) to other continents or dungeons so it needs more research if it is possible to keep swimming state and potentially be a game breaking bug

The trick is frame perfect or close to it and only me and Aegean know how to create it so there shouldnt be any worries other players using it and getting falsely flagged as cheaters.

**Comment by Smuganimegrl** [comment]
As an addition, I can reproduce the bug if other gms or devs want to see it in action since its pretty hard to explain in words

**Comment by areus1** [comment]
Sorry to burst your bubble but this is a known bug, and is doable anywhere on the map flying is possible. However it doesn't persist through any hearthstone, lock summon, mage portal, or instance portal. I discovered this doing the dailies to unlock shadowvault. Won't say exactly how it's done, but you don't need to be on any quest.
