### ISSUE TITLE
Warrior Berserker stance quest

### ISSUE THREAD

**Issue by nozgaara** [OmegaWoWeu/Decades#26]
Description:, Klannad Macleod has a mark for the quest over his head but i cant start the quest. he only says "greetings" but there is no way for me to start the quest. There is no quest in his dialogue..... Charakter: Retardead

How to reproduce bug:

How it should work: I talk to him and there will be a quest in the Chat.

Screenshots:

Relevant AddOns used: i dont have addons at the momend

Source:

**Comment by bobarata** [comment]
fix that quest !
bump!

**Comment by nozgaara** [comment]
it works again on my char since this morning. Thanks
