### ISSUE TITLE
[Loot] Need roll after releasing 

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#27]
Description:
 it is reported that if a player die in the fight and select need roll for and item then select "release spirit" it doesnt Count his need rolls

How it should work:it supposed to Count players need roll

Screenshots:
![wowscrnshot_020219_143225](https://user-images.githubusercontent.com/47177389/52164671-2f67d180-270a-11e9-8922-74aaef43a399.jpg)

Source: player named najara

**Comment by OmegaWoWeu** [comment]
https://worldofwarcraft.fandom.com/et/wiki/Release_Spirit

"You will not be able to loot or roll on loot on mobs that die after you release."

worldofwarcraft.fandom.com is not exactly the most reliable source, though, so I would ask anyone reading this if they can provide a reliable source that says you are still eligible for loot from a boss that is still being fought when you release.

In situations where need/greed loot rules are in place, not Master Loot.

**Comment by blzee** [comment]
Invalid report, you’re not eligible for loot if you release upon bosses death.
