### ISSUE TITLE
[Npc] aextrasza

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#28]
Description:
After compeleting and giving in  the Quest named "on ruby wings "  ,aextrasza doesnt the next quest named "return to angrather"

How it should work: aextrasza should give the quest "return to angrather" its part of a chain 

Source: https://wowwiki.fandom.com/wiki/Quest:The_Battle_For_The_Undercity_(Alliance)

**Comment by OmegaWoWeu** [comment]
If it's not already enabled (Horde), it will be tomorrow.
