### ISSUE TITLE
[quest] investigate the blue recluse

### ISSUE THREAD

**Issue by Pogodenhelder** [OmegaWoWeu/Decades#3]
Description:[quest] the blue recluse

How to reproduce bug:
go the blue recluse, when you use the item the mana rifts spawn, but they hit in a massive rapidly interfall, its an old bug, they come with 2 of them down from the stairs, it takes 3 seconds to wipe my ass of the floor, no way you can do that quest this way.
How it should work:
they should not attack that fast.. and maybe even not come in pairs but 1 in a time.
Screenshots:
![schermafbeelding 2019-01-27 om 12 10 45](https://user-images.githubusercontent.com/35499601/51800293-5cf5dc00-222d-11e9-870b-77c7b3b332e7.png)

Relevant AddOns used:
automatic goblin therapist for assholes that whisper me.
Omegawow gm ticket addon.. could work.. but im no gm so meh 👍 
Questhelper

Source:
my own experience that this is not doable MOEHAHA

**Comment by OmegaWoWeu** [comment]
This quest works as intended.
