### ISSUE TITLE
[Spell] Rouges reported issues

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#31]
Description:
mobs dodge my attacks while they are stunned with cheap shot  thats not supposed ot happen to dodge block or parry while you are incapacited with stun fear blind etc ,also mobs dodge when attacked from behind, you an only miss due to lack of expertise weapon attacking opponent,but not dodge defensive returns are not possible from behind just as when you are stunned thank you for

Source: player named lethatlity

**Comment by OmegaWoWeu** [comment]
Report is missing information or did not respect guidelines.
