### ISSUE TITLE
[Npc] Lured clossus

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#32]
Description:

The monster ''Lured Colossus'' that spawns at Cenarion Outpost before u can begin the quest ''Natural Remedies'' Does way too much damage and attacks too fast. He does 2k damage per hit while the average player around this level has a healthpool of 4k

**Comment by OmegaWoWeu** [comment]
Lured Colossus is part of a group quest, as as such is an Elite. It is meant to be tackled by a group containing a tank and a healer.

Damage is Blizzlike!
