### ISSUE TITLE
[spell] cheapshot [rogue]

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#33]
Description:
 when you cheapshot a mob you recive in the very same moment when you are cheap shotting you recive an attack and than moster goes into stun witch is not supposed ot be because  you are stealted you cheap shot and monster is stunned not the way you cheap shot you get basic attack while casting it

**Comment by OmegaWoWeu** [comment]
Report is missing information or did not respect guidelines.
