### ISSUE TITLE
Fishing Events

### ISSUE THREAD

**Issue by bieliqus** [OmegaWoWeu/Decades#34]
Description: STV extravaganza starts too early, i'm not sure if kaluak fishing derby works correctly because people were fishing and none won (I myself caught hundreds of suckerfish during 1 hour period).

How to reproduce bug: -

How it should work: STV extravaganza should start at 2 pm. Can you check if Kaluak fishing derby works? I know its RNG but still no winner, smth smells fishy.

Screenshots:
https://imgur.com/a/ptCt3sq

Relevant AddOns used:

Source:
https://wotlk.evowow.com/?event=15

**Comment by alecagha** [comment]
I’ve had this problem on other servers. It would always start an hour early, or even 2 on one server. It supposedly just relates to daylight savings time i.e. the server clock updates but the events don’t.

No need to fix, it makes it easier to win for us who know about this xd

**Comment by blzee** [comment]
It works, I’ve done it on my character to confirm.
