### ISSUE TITLE
[ NPC ] : Thrall model missing

### ISSUE THREAD

**Issue by GMShepherdOW** [OmegaWoWeu/Decades#35]
Description: NPC Thrall in Nagrand > Garadar has his model missing

How to reproduce bug: Go to Garadar and find thrall, you only see a weapon

How it should work: He should have a model

Screenshots: http://prntscr.com/mg40zb
 
Relevant AddOns used:

Source:

Comment: Used .morph 4527 as a temporary fix (Thrall model )

**Comment by blzee** [comment]
Thank you for your report, forwarding to a dev.

**Comment by OmegaWoWeu** [comment]
Fixed.
-Bliss
