### ISSUE TITLE
Explosive Trap

### ISSUE THREAD

**Issue by Undertower** [OmegaWoWeu/Decades#36]
Description:
The damage of Explosive Trap is updated dynamically, meaning the initial damage, as well as the damage over time effect,  will be affected by changes to your AP or Damage Modifier after the ability has already been used rather than being snapshot at cast.

How to reproduce bug:
Cast Explosive Trap on a target and then switch to Aspect of the Viper after it hit/the cast to see immediate damage change.

How it should work:
The AP contribution, damage modifier, crit chance and crit damage modifiers should all be snapshot at the cast and should be unaffected by future changes to the hunter.

Screenshots:
![wowscrnshot_020419_005144](https://user-images.githubusercontent.com/44290478/52184926-db4c1280-2819-11e9-8a8f-bcb2925fc054.jpg)
![wowscrnshot_020419_005146](https://user-images.githubusercontent.com/44290478/52184927-db4c1280-2819-11e9-9a1f-4a323095bc87.jpg)

Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
Report is missing information or did not respect guidelines.
