### ISSUE TITLE
Pet movement speed

### ISSUE THREAD

**Issue by Undertower** [OmegaWoWeu/Decades#37]
Description:
The Movement Speed of the pet is extremely strange. It appears to be linked to the Hunter's movement speed.

How to reproduce bug:
Send your pet at a target that's far away while you do something that affects the movement speed of the hunter, such as changing into Aspect of the Pack or Aspect of the Cheetah, or the pet itself by using Dash.

How it should work:
The movement speed of the hunter's pet should be a separate entity and not linked to the hunter in any way.

Screenshots:
https://i.gyazo.com/8aec34de4e55c77bc51e02abdff18919.mp4
https://i.gyazo.com/8b3258b975c32febb3f488747a468f4b.mp4

Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
Report is missing information or did not respect guidelines.
