### ISSUE TITLE
Lightwell is not working as intended

### ISSUE THREAD

**Issue by Poppeboy** [OmegaWoWeu/Decades#38]
Description:
When I use my spell "Lightwell" as a holy Priest it says it has 10 charges. The problem is that each person can only interact with it once.
How to reproduce bug:
Just click the lightwell for a heal and then it just stays there.
How it should work:
Every person should be able to consume as many charges as you like (as long you keep it under a total of ten uses per Lightwell)
Screenshots:
I do not have a screenshot sorry. Got tired of it so I respeced, and therefore I do not have that talent.
Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
Report is missing information or did not respect guidelines.
