### ISSUE TITLE
Throwing puts you in combat before the hit lands

### ISSUE THREAD

**Issue by sicknot1** [OmegaWoWeu/Decades#4]
Description:
Throwing puts you in combat before hit lands
How to reproduce bug:
target mob, cast throwing weapon, gets in combat
How it should work:
Casting the throwing shouldn't put you in combat, only when it hits
Screenshots:
![wowscrnshot_012719_135812](https://user-images.githubusercontent.com/35937937/51804139-aa794580-223b-11e9-8381-deb18b828a7c.jpg)

Relevant AddOns used:
gotta take a pic later

Source:

**Comment by OmegaWoWeu** [comment]
Report is missing information or did not respect guidelines.

**Comment by sicknot1** [comment]
Well then fuck you retard on your doa server with stock mangos bugs jesus christ you really want me to put a long ass description for free for a DoA server? should be thankfull i even took the effort to make the report.

HOW TO REPRODUCE BUG
BE WARRIOR
/EQUIP THROW WEAPON
/TARGET MOB
/CAST OR CLICK THROW 
/INSTANTLY IN COMBAT
/IS IT COMMON KNOWLEDGE WARRIORS CAN DO THROW AND THEN CHARGE BEFORE THE HIT LANDS

AMATEUUUUUUUUUUURSSSSSSSSSSSS
