### ISSUE TITLE
Mob autoattack after cheapshot

### ISSUE THREAD

**Issue by bloodsugar** [OmegaWoWeu/Decades#40]
Description: After a rogue cheapshots a mob, he recives 1 autoattack. 

How to reproduce bug: Level a rogue until u can learn cheap shot, run to a mob, stealth and cheap shot it. You will recive instant autotattack before the stun begins. Not sure if only happens with mobs, maybe with player pets and guardians as well.

How it should work:
Shouldnt recive an autoattack since you were stealthed AND used a stun. 
Screenshots: Will update later in the day

Relevant AddOns used:
 none
Source: player

**Comment by bloodsugar** [comment]
![image](https://user-images.githubusercontent.com/16647648/52292863-ea47d780-2975-11e9-8443-04ba3cf383bd.png)

**Comment by RodaxQA** [comment]
+1, and cheapshot has like 0.3/0.4sec delay before effect, curious

**Comment by blzee** [comment]
Can confirm this, also happens with druid pounce. Thank you for your report, forwarding to a dev.
