### ISSUE TITLE
[ Profession NPC ] Stephen Ryback

### ISSUE THREAD

**Issue by GMShepherdOW** [OmegaWoWeu/Decades#42]
Description: Cooking trainer taking your money for Journeyman cooking but not teaching you the skill

How to reproduce bug: Get cooking to 50 and try to learn Journeyman cook from him

How it should work: It should teach you Journeyman cooking

Screenshots: http://prntscr.com/mh08rd

Relevant AddOns used: /

Source: /

**Comment by OmegaWoWeu** [comment]
Now works.
