### ISSUE TITLE
Pet movement speed

### ISSUE THREAD

**Issue by Undertower** [OmegaWoWeu/Decades#43]
Description:
The Movement Speed of the pet is extremely strange. It appears to be linked to the Hunter's movement speed.

I recorded some times for the pet to run 100 yards with various modifiers:
No Speed boosts: 15.16
Boar's Speed Talent: 12.01
Boar's Speed + Dash: 3.08
Boar's Speed + Dash + Aspect of the Pack: = 2.27
Boar's Speed + Dash + Aspect of the Pack + Pathfinding + Kindred Spirits = 1.55s

How to reproduce bug:
Send your pet at a target that's far away while you do something that affects the movement speed of the hunter, such as changing into Aspect of the Pack or Aspect of the Cheetah, or the pet itself by using Dash.

How it should work:
The movement speed of the hunter's pet should be a separate entity and not linked to the hunter in any way while in combat.

Screenshots:
https://i.gyazo.com/8aec34de4e55c77bc51e02abdff18919.mp4
https://i.gyazo.com/8b3258b975c32febb3f488747a468f4b.mp4

Relevant AddOns used:

Source: Common sense.

**Comment by OmegaWoWeu** [comment]
This is not true; the pet should gain every positive effect from the owner, but none of the negative ones. So, it's a separate thing, but your pet should gain all the positive effects. If you think this is wrong, please provide a source / proof.
