### ISSUE TITLE
The Islander quest line

### ISSUE THREAD

**Issue by bobarata** [OmegaWoWeu/Decades#45]
Description:i have a problem with quest: The Islander quest for Berserker stance - Npc not giving me the 2-nd quest  The Affrey .The "!" mark is on but when i speak with him he told me: Greatings...

How to reproduce bug:

How it should work:He has give to me the quest 

Screenshots:

Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
Seems to work for me. Could you confirm it is still bugged for you? Post pictures of the "Greetings" gossip text if yes.

**Comment by blzee** [comment]
Quest works as intended, delete your cache if you’re having an issue or review your addons.
