### ISSUE TITLE
[Quest] [Leading the ancestors home] broken

### ISSUE THREAD

**Issue by sicknot1** [OmegaWoWeu/Decades#46]
Description:
Quest broken
How to reproduce bug:
Do quest
How it should work:
When you right click on totem it should count (read quest)
Screenshots:
![wowscrnshot_020619_123432](https://user-images.githubusercontent.com/35937937/52352639-be773100-2a0b-11e9-87ca-fb5bb6fd193b.jpg)
![wowscrnshot_020619_123434](https://user-images.githubusercontent.com/35937937/52352652-c505a880-2a0b-11e9-9aa9-62032dae35d5.jpg)

Relevant AddOns used:

Source: The game... ??????????????? jeez

**Comment by bobarata** [comment]
it seems no one give a fuck about bugz and stuff here ...

**Comment by blzee** [comment]
Invalid report, quest works as intended.
