### ISSUE TITLE
[Spell] Hunter's replenishment is causing agro

### ISSUE THREAD

**Issue by Lunasoll** [OmegaWoWeu/Decades#47]
Description: Survival hunter's have talent called "Hunting Party" which gives 'Replenishment' if spells crit. It's causing aggro for some reason when only healing spells such as mend pet supposed to do that. 

At the moment it's hard to quest/level as Survival because pet just can't hold aggro long enough when Replenishment is procced. 

How to reproduce bug: Have a Survival Hunter with 'Hunting Party' talent skill pull two mobs with pet aggroing them both. Then damage one of them till 'Replenishment' procs. The second mob will aggro on hunter, even though it wasn't damaged by hunter. 

How it should work: Replenishment shouldn't cause any aggro. 

Screenshots:

Relevant AddOns used:

Source: In-game

**Comment by bieliqus** [comment]
Same thing happens with innervate.

**Comment by Snotshots** [comment]
Replenishment gives a buff. Buffing generates threat, as do mana gains. Working as intended.
