### ISSUE TITLE
Glyph of Shadow Protection (Minor Glyph) bug

### ISSUE THREAD

**Issue by Tadi93** [OmegaWoWeu/Decades#48]
Description:Glyph of Shadow Protection (Minor Glyph) won't apply on glyph tab with elvui

How to reproduce bug: right click on glyph in inventory and can't click on minor glyph ball (either of them) to apply glyph

How it should work:right click on glyph in inventory, left click to apply(double click with approval to overwrite) 

Screenshots: https://i.imgur.com/b7Kgqwz.png

Relevant AddOns used: elvui https://github.com/ElvUI-WotLK/ElvUI

Source:

**Comment by OmegaWoWeu** [comment]
So this is an issue with only using ElvUI?

If that's the case, it's a problem with the AddOn, and not on our end of the code.

**Comment by alecagha** [comment]
It’s most likely the known bug relating to duel spec on all wrath servers; if you a minor glyph on one spec, and then try to apply the same glyph on your other spec, it won’t let you. Fix is simple if this is the case: just fully restart your client and log back in.

If it’s not the duel spec issue then forget I said anything.

**Comment by blzee** [comment]
Having the same glyphs on both specs is working without problems, if it’s still happening I suggest reviewing your addons.
