### ISSUE TITLE
[Quest] [Mistery of the infinite] Invisible future you/mobs under textures

### ISSUE THREAD

**Issue by sicknot1** [OmegaWoWeu/Decades#49]
Description:
It's a quest in wich you place a hourglass and have to defend it, your future self appears, but it's invisible, some mobs (also caster mobs) are under the mound in the center of the area (see pics)
How to reproduce bug:
Do the quests
How it should work:
Your future self should be in corporeal form(?) and mobs shouldn't be under textures
Screenshots:
![wowscrnshot_020719_124530](https://user-images.githubusercontent.com/35937937/52423448-ebdce100-2ad6-11e9-89b5-2df63e0d76cd.jpg)
![wowscrnshot_020719_124600](https://user-images.githubusercontent.com/35937937/52423452-eed7d180-2ad6-11e9-925c-550833ed0a3b.jpg)
![wowscrnshot_020719_124659](https://user-images.githubusercontent.com/35937937/52423500-04e59200-2ad7-11e9-88fd-73c0c33bc2cc.jpg)

Relevant AddOns used:

Source: The quest / Screenshoots uploaded (seems a visual bug+ Vmaps bug)

**Comment by SovereignBan** [comment]
You don't need to necessarily place the hourglass there, you can put it on flat surface just a little to the right where you are.

Speaking of, i did mine just a few minutes ago, i placed the hourglass where you have and they didn't spawn in the mound, nor were they invisible, they spawned normaly.
