### ISSUE TITLE
Meta Gem (Probably Scripting Bug - GM's assumption)

### ISSUE THREAD

**Issue by Tadi93** [OmegaWoWeu/Decades#51]
Description: 
I have this meta gem https://wotlk.evowow.com/item=41401 and it doesn't proc at all. I have similar enchantment on my cloak which works fine ( +400 mana proc). I tried without cloak to see does it works, won't proc at all. 

NOTE:
One druid has this gem too and it procs for him normally.
How to reproduce bug:
Casting all kind of healing spells ( holy priest) and won't proc at all
How it should work:
i read somewhere it has proc rate 1 per min (600+ mana) but i can't be sure about it. 
Screenshots:
https://i.imgur.com/hxk5ycg.png
https://i.imgur.com/hAvBMOo.png
https://i.imgur.com/JhfNqgr.png
https://i.imgur.com/uOR4XYV.png (note: waist has prismatic socket ( i put yellow here(first was red and yellow-tried both to see if it works) 

Relevant AddOns used:elvui

Source:
https://wotlk.evowow.com/item=41401
It should proc 600+ mana restore

**Comment by Tadi93** [comment]
Not sure, but probably worked after i changed to shadow spec and back. i gain +600 mana proc

**Comment by OmegaWoWeu** [comment]
Can someone else confirm this is working? If it works for two people, then it's not a bug.

If it doesn't work the first time, switch specs like Tadi93 did and check then.

**Comment by Tadi93** [comment]
Thanks for replying. I Got upgrades from raid and new meta head epic. I didn't had any yellow gem to put.. but i could make prismatic gem on belt (extra socket). I put yellow there and meta gem is activated(white). but won't proc that gem mentioned above. I'm pretty sure prismatic socket doesn't work as it should. I tried as i did above and won't work. Im pretty sure prismtic socket doesn't activate yellow gem properly, thus making meta gem inactive

**Comment by Mental26** [comment]
> Can someone else confirm this is working? If it works for two people, then it's not a bug.
> 
> If it doesn't work the first time, switch specs like Tadi93 did and check then.

Yes I can confirm. The meta itself works if you got the specific gems equipped but if you have prismatic ones (I'm a JC with 3 prismatic) the meta passive is not activating at all. If you need more evidence I can make a short video. 

Please fix this issue because for healers (especially Hpala) this is a BIS meta gem.

EDIT: It is working for the people who have the necessary  unique gems (1 red, 1 yellow, 1 blue) equipped but if you have let's say 1 red 1 yellow and 3 prismatic (which should count as any color) is not working. So the problem itself is not the meta gem, but the fact that prismatic gems are not counted as "colors".

**Comment by alecagha** [comment]
Just wanna add onto this if prismatic isn’t activating it properly. You should only need ONE prismatic to activate it, as it requires ONE red blue and yellow, which the prismatic covers simultaneously.

Idk why you are using 3 in the first place @Mental26 but I just don’t want to leave any room for confusion for the devs.

**Comment by alecagha** [comment]
I can confirm this is not a bug. I've tried activating the meta both with normal gems and with a prismatic in diff raid settings, and in both cases I have logs of gaining the buff from it ("Mana Restore")

Here's a couple small pics if you don't believe me but it's not like this really shows my diff gemming. 

![](https://i.gyazo.com/5d24e56f66938c373d88afce6ae8a531.png)
![](https://i.gyazo.com/b1e74ae2698e2ff7eca9f285c927299e.png)
