### ISSUE TITLE
Return To Angrathar quest (Horde side)

### ISSUE THREAD

**Issue by GoldenE89** [OmegaWoWeu/Decades#52]
Description: Return To Angrathar quest cannot be taken

How to reproduce bug: Complete the quest chain until you finish the On Ruby Wings quest, after that Alexstrasza should offer the Return To Angrathar quest, that leads to the wrathgate cinematic and to the siege of Undercity, but the quest is nowhere to be found.

How it should work: After completing the  On Ruby Wings quest, the player should be able to get it from Alexstrasza.

Screenshots:
https://i.imgur.com/DdbLvYi.jpg

Relevant AddOns used: Only QuestHelper

Source:
https://www.wowhead.com/quest=12498/on-ruby-wings
https://www.wowhead.com/quest=12500/return-to-angrathar

**Comment by OmegaWoWeu** [comment]
Quest line can now be continued.

If you can't see the next phase after the Return to Angrathar quest, exit the zone and re-enter it (Court of Skulls to be exact).

**Comment by GoldenE89** [comment]
Works like a charm :)
