### ISSUE TITLE
[Hunters] Aspect of Viper doesn't work with Volley

### ISSUE THREAD

**Issue by SovereignBan** [OmegaWoWeu/Decades#53]
Description: When you play Hunter ofc you have struggles with your mana management most of the time, but that was always taken care of when a pull on trash gathered more than 2-3 of them and you could use volley in combination with Aspect of the Viper to quickly replenish a big amount of your mana, but here it doesn't work.

How to reproduce bug: Activate [Aspect of the Viper] and use Volley on a mob.

How it should work: When Aspect of the Viper is active your volley skill regenerates your mana quickly as it recognises each target hit as an individual target and restores your MP for each one of them affected by it.

Screenshots:

Relevant AddOns used:

Source:

**Comment by blzee** [comment]
That is actually false, volley/viper aspect is working as intended.
https://wowwiki.fandom.com/wiki/Aspect_of_the_Viper

How it should work:
Aspect of the Viper causes each ranged attack (including the initial application of Serpent Sting, all three charges of Explosive Shot, all three missiles of Multi-Shot, but not including the ticks of Serpent Sting or the damage of Volley) to generate a percentage of the Hunter's maximum mana.
