### ISSUE TITLE
Pets disappearing from the Stables.

### ISSUE THREAD

**Issue by Lolapops** [OmegaWoWeu/Decades#55]
Description:
I've lost 2 pets so far to this bug, my lvl 80 devilsaur and lvl 74 spirit beast Arcturis. It appears that pets can disappear from the stable somehow. 
How to reproduce bug:
Put a pet into the stable and wait. 
How it should work:
Pets should stay in the stable untill swapped and not run away like the sneaky pets they are.
Screenshots:
Have not taken any screenshots of the pets themselves, but know many players on the server who can tell you that i had them.
Relevant AddOns used:
No particular addons used.
Source:
Experience in game

Additional info:
I've got dual spec and i can see the pets in both specs. I just can't equip them in marksman or survival.
I've tried deleting the cache and WTF folders to see if they reappeared - They didn't.
I read on another forum that there was a bug in retail wow that caused pets to disappear if they died during combat occasionally(Though that shouldn't affect stabled pets).

**Comment by vergon6** [comment]
I have experienced this issue as well. I had 2 pets in stable and tried switching one with my active pet. The active pet disappeared

**Comment by Lolapops** [comment]
Update:
I've lost 2 pets across the last 2 days. Both of them was the spirit beast Skoll. Lost him and recaptured, now lost again. First time i lost one using the hunter skill "Call Stable Pet". My active pet overrid Skoll i was trying to take out. It doesn't matter if you put your pets in an empty slot or exchange them directly, they will just override and disappear.

**Comment by jus7dev** [comment]
Please, fix this as it is game breaking. Hunters need at least 2 pets, one for pve and one for pvp. We cannot change pets due to this bug.

**Comment by SirRestraint** [comment]
Hello,
i did encounter same issue.
After i used "Call stable pet" and swapped my active pet (devilosaur) for stabled pet (monkey), the devilosaur went to stables but monkey did not appear.
Monkey disappeared completely and devilosaur was in stables.

EDIT: both pets lvl80

**Comment by blzee** [comment]
Thanks for your report.

**Comment by Sephirla** [comment]
Hi, 
Pets are still vanishing from stables, i have lost at least 10 pets yet.
