### ISSUE TITLE
Death Knight Threat issues

### ISSUE THREAD

**Issue by IamR00l** [OmegaWoWeu/Decades#57]
Description: Death and Decay and Blood Boil, and I think Howling Blast all have threat scaling bugs. if had to guess, DnD and BB have maybe 1/10th their normal threat if not worse. I would maybe go through all of the threat numbers on any spell. Single target is no problem with Icy Touch spam, but everything else is difficult.

How to reproduce bug: Use the spells,and watch Omen

How it should work: More threat.

Screenshots:

Relevant AddOns used: Omen

Source:

**Comment by blzee** [comment]
Invalid report, missing proof/source.
