### ISSUE TITLE
The Warsong Reports Quest Bug

### ISSUE THREAD

**Issue by Cyanizzle** [OmegaWoWeu/Decades#6]
Description:
During The Warsong Reports quest, you must deliver messages to horde runners throughout ashenvale, the reports dissapeared after the second outrunner and now I can't finish the quest
How to reproduce bug:
Hand in report at splintertree post and to the outrunner, go to Zoram strand and when you go to hand in the final part you cant hand it in as theres no more report
How it should work:
You hand in the final report and get the final warsong update
Screenshots:
![image](https://user-images.githubusercontent.com/26595109/51841732-2e4c3400-2307-11e9-8edd-fd61ad3d9f03.png)

Relevant AddOns used:
bagnon Bartender questhelper
Source:

**Comment by OmegaWoWeu** [comment]
We were unable to reproduce the issue.
