### ISSUE TITLE
Strand Of The Ancients Bug.

### ISSUE THREAD

**Issue by reckted** [OmegaWoWeu/Decades#60]
Description:Demolishers in Strand of the Ancients can get Sacred Shield casted on them.

How to reproduce bug: Get inside Strand of the ancients, Cast sacred shield as Paladin on Demolisher.

How it should work: Demolishers should be immune to any kind of shields, or, which i didn't get a chance to test, Judgment of Justice slow. 

Screenshots:Sadly, didn't take, will upload on next SoTa, but easy to reproduce.

Relevant AddOns used:none 

Source: Omegawow

**Comment by Mloentje** [comment]
So  when you gm's said it will be faster to help you if you post on the forums , 
when is the help coming ???
 i wanna move on with my game... 
when i know you can just complete or  restart my chain with a button...
i have had this happen on old omega and then gm's just reset my questline or even  just made it that i could complete the quest in 2 minuts 
3 days....and still no word....

**Comment by blzee** [comment]
Thank you for your report.
