### ISSUE TITLE
Two-hand mace skill not moving from 0

### ISSUE THREAD

**Issue by nenadly** [OmegaWoWeu/Decades#61]
Description: Learnd two-hand mace skill cant skill it 

How to reproduce bug: learnd two-hand mace skill in ironforge 

How it should work: it should go up from 0 to 450 

Screenshots:

Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
Are you trying to learn it on low-level mobs or target dummies instead of mobs near your level?
