### ISSUE TITLE
Vehicles in Wintergrasp receiving heals

### ISSUE THREAD

**Issue by reckted** [OmegaWoWeu/Decades#63]
Description: AoE heals seem to effect vehicles in Wintergrasp. Didn't test it on direct heals.

How to reproduce bug:Get inside WG and try to heal vehicle.

How it should work:no vehicles should receive heals, or healing auras.

Screenshots:
![wowscrnshot_021419_192050](https://user-images.githubusercontent.com/47602690/52808665-b1eb7c00-308e-11e9-86aa-8e49f9e11c0b.jpg)

Relevant AddOns used: none

Source: Omegawow

**Comment by Absolution2015** [comment]
What do you mean by AOE heal? There's no combat log, so which spell do you mean specifically.

I'll mention Blood Pact is a health boost aura, not a healing aura.

Could also use some references from retail sources that show WG vehicles can't be affected by auras.

**Comment by reckted** [comment]
do you not see wild growth druid healing aura on it? Or i can try in next WG cast Sacred Shield on it, and post Screenshot here also. 
p.s. sorry for slow reply, didn't check my mail in days..
