### ISSUE TITLE
The fishing skill is missing from Mastercraft Kalu'ak Fishing Pole.

### ISSUE THREAD

**Issue by NathanNatNat** [OmegaWoWeu/Decades#65]
Description: The fishing skill is missing from Mastercraft Kalu'ak Fishing Pole.
https://wotlk.evowow.com/?item=44050
should have +30 fishing skill, i have cleared cache and still dont see any fishing skill. other people also see the same issue.
should have: https://wotlk.evowow.com/?spell=59731

**Comment by OmegaWoWeu** [comment]
Confirmed. It actually has some weird Druid buff equip instead of the Fishing Skill one.

**Comment by NathanNatNat** [comment]
probably a typo when it was added
