### ISSUE TITLE
Warrior - stances

### ISSUE THREAD

**Issue by blzee** [OmegaWoWeu/Decades#66]
Description: Whenever you come out of a dungeon with RDF, Teleport in or out of WG, exit vehicles etc, it completely takes you out of any stance you’re in. Eating up a gcd just to restance & rage dumps

How to reproduce bug: do one of the things I mentioned

How it should work: stay in the stance you were currently in before entering/exiting

Screenshots: can’t, on my phone. Unless you want a shitty phone pic 

Relevant AddOns used: DBM, SFKP, bagnon, aesa

Source: tested, me

**Comment by NathanNatNat** [comment]
I can confirm this, also happens when leaving the Decay flesh phase of The Prophet Tharon'ja fight in Drak'Tharon Keep and some other stuff as well like leaving vehicles.
