### ISSUE TITLE
Warrior sweeping strikes

### ISSUE THREAD

**Issue by blzee** [OmegaWoWeu/Decades#68]
Description: thunderclap is consuming all 5 stacks of sweeping strikes, also some abilities IE slam/heroic strike is consuming multiple stacks at once 

How to reproduce bug: do one of the things I mentioned above.

How it should work: well thunderclap shouldn’t consume any stacks, 3.3 thunderclap counts as a ranged attack so. Also slam/heroic strike should only consume 1 per use.

Screenshots: on my phone, I can’t. Unless you want a shitty phone quality pic

Relevant AddOns used: DBM, bagnon, aesa, SFKP

Source: (2010-03-23): This ability now counts as a ranged attack, granting it double damage on critical strikes instead of 150% and ranged miss chance, and still cannot be dodged or parried.

**Comment by OmegaWoWeu** [comment]
Hurii: I can't reproduce thing with heroic strike or slam - they're looking fine, probably you did count them with autoattack as well. Thunderclap is fixed and whole ability shoudln't take charges from anything that is not melee now.
