### ISSUE TITLE
Wintergrasp - Essence of Wintergrasp

### ISSUE THREAD

**Issue by blzee** [OmegaWoWeu/Decades#69]
Description: Controlling wintergrasp isn’t giving the faction the buff *Essence of wintergrasp* allowing for stone keep shard collection 

How to reproduce bug: win WG

How it should work: give you the buff upon winning WG and allow collection of shards in wotlk dungeons

Screenshots: on my phone, can’t. Ask anyone on the server.

Relevant AddOns used: bagnon, dbm, aesa, SFKP

Source: me

**Comment by OmegaWoWeu** [comment]
Fixed.
