### ISSUE TITLE
Unable to prospect Titanium Ore

### ISSUE THREAD

**Issue by Undertower** [OmegaWoWeu/Decades#7]
Description: 

When I attempt to prospect Titanium Ore I get an error message saying: "There are no gems in this."

How to reproduce bug:
Attempt to prospect Titanium Ores.

How it should work:
Prospecting Titanium Ore should work.

Screenshots:
![wowscrnshot_012819_183524](https://user-images.githubusercontent.com/44290478/51854753-cb20c880-232b-11e9-8758-dd1b107583d9.jpg)

Relevant AddOns used:

Source:

**Comment by Absolution2015** [comment]
Prospecting Titanium was added in patch 3.2, so it does technically work as it should.
