### ISSUE TITLE
Nesingwary 4000 not providing the damage shown in the tooltip.

### ISSUE THREAD

**Issue by Bigmoist69** [OmegaWoWeu/Decades#71]
Description: Nesingwary 4000 gun made from Engineering is not providing the damage shown in the tooltip. Notice in the screenshots how my AP is higher with the Nesingwary 4000 equipped yet I have less damage. And if you look up the gun in the database you will see it has higher base and max damage than Pierce's Pistol.

How to reproduce bug: Seems that all you need to do is equip it. 

How it should work: Should give more damage.

Screenshots: Here I am with Pierce's Pistol equipped: https://gyazo.com/3451db846fbd4773cb35d02cc89b09c7

Here I am with Nesingwary 4000 Equipped: https://gyazo.com/9bf4d5b9bc762ef05fa0ac0387510b9b

Relevant AddOns used: Gearscore, DBM, Quartz, Skada, Recount (disabled), OmenThreat (disabled), Atlasloot

Source: https://wotlk.evowow.com/?item=44504
https://wotlk.evowow.com/?item=37692

**Comment by Grievuuz** [comment]
Damage calculation takes your attack power into account as well. 

The fact that the Nesingwary 4k is just slightly faster and only does slightly more base damage is what results in your damage per attack doing slightly less damage but each bullet is also slightly faster.

Nothing wrong here :)

**Comment by blzee** [comment]
Working as intended, above comment pretty much explained it right.
