### ISSUE TITLE
RDF Satchel not providing items when opening

### ISSUE THREAD

**Issue by ghost** [OmegaWoWeu/Decades#72]
Description:
The past 5 dungeons when receiving the satchel , it vanishes on click and no items are looted. This started happening on Sunday 2/16/2019.

How to reproduce bug:
Run normal:
Sethekk Halls
Mana Tombs
Hellfire Ramparts
Blood Furnace

How it should work:
When clicking the satchel, an item should be looted

Screenshots:
Video of the loot issue happening: https://youtu.be/iMD7tlAhpUA

Relevant AddOns used:
ElvUI , DBM, GearScoreLite

Source:

**Comment by Warmanesucks** [comment]
14 days ago..

**Comment by OmegaWoWeu** [comment]
Can't reproduce this issue.
