### ISSUE TITLE
"Heigan the Unclean" - Safety Dance

### ISSUE THREAD

**Issue by Arcadios3976** [OmegaWoWeu/Decades#73]
**Description:** During the safety dance on the Heigan the Unclean fight in both 10/25m the hitbox for the Eruption spell is larger than intended. There are many spots in the safe zones where people still get hit by the spell.

**How to reproduce bug:** Watch half my raid die in the "safe zone" 

**How it should work:** Should only be hit by Eruption in the visual areas where the spell is going off

**Screenshots:** Forgot to take any, but here is a picture of the eruption areas. A lot of people are getting hit in the middle of the Zone marked number 2
http://smg.photobucket.com/user/firelordgd/media/WoWScrnShot_122208_001233.jpg.html

**Comment by Grievuuz** [comment]
You're probably not gonna see an official answer, as this is 100% an intended buff to the encounter. I was able to successfully pug it on 25m where 23 people were alive at the end - by using smoke flares to mark safespots and aspect of the pack to get everyone to safety in time.

**Comment by blzee** [comment]
The change was intended. Can’t be to far or close.
