### ISSUE TITLE
Flight Form momentum

### ISSUE THREAD

**Issue by ghost** [OmegaWoWeu/Decades#74]
Description:

Exiting Flight Form while flying in any direction resets the character's momentum to walk speed. It should just keep the flight form's momentum like regular flying mounts. This vid describes the bug (it was made for another server but it's the same here) https://youtu.be/cGrGEfDh15w

How to reproduce bug:

1. Move in any direction with flight form
2. Exit flight form
3. Your character starts falling forward at walk speed

How it should work:

Like any regular flying mount : if you dismount while moving in any direction, your character keeps his momentum.

Source:

2010 vid of a guy testing flight form on what can probably safely be assumed to be retail https://www.youtube.com/watch?v=Q_zJLDE1-sk&feature=youtu.be&t=93

Edit : found out that regular flying mounts were not supposed to conserve momentum when dismounting before 5.1 when it was changed. Apparently (around 5.0) druid flight forms were special in that regard, but I'm still unsure if they always were. Some comments seem to point out that they always have been, though (ever since tbc). source : https://us.battle.net/forums/en/wow/topic/7414952408?page=2 "It has always been a mechanic of the Druid flight form. I had always wished normal mounts would do the same. Only difference is you cannot remount in midflight like druids can (shapeshift to flight form)."

**Comment by blzee** [comment]
I’m having difficulties mirroring the bug, it works perfectly fine for me going in and out of flight form, also the other druids I’ve talked to as well. Could you provide further proof?

**Comment by ghost** [comment]
The second video I linked shows how it's supposed to work. Here's another one https://youtu.be/76dFyBPgVyw?t=56

If you look closely, you'll notice that when the druid drops his flight form while moving forward, his horizontal speed does not decrease.

Here on OmegaWoW, if a druid does this, his horizontal speed drops to walk speed. Fly towards a ledge. As you near it, drop your flight form. The retail behavior is that you keep your high speed, so you'll reach the ground and land on the ledge. The behavior here is that your speed is reset back to walk speed, you fall almost straight down, and you miss the ledge.

The very first vid I linked clearly shows the difference.

There's something I'm not quite sure about, and I can't find any vid on this : vertical speed.

The way it works on retail now (BfA - and it works like this on regular flying mounts as well, though this was changed at MoP) is that you keep your momentum in whatever direction. Say you were flying straight up, drop your mount/flight form, your character will just fly upwards for a few more seconds, slow down, reach the apex of the "jump", then fall back down. If you were flying straight down, same thing : you drop straight down with no horizontal speed. It's just how real physics would work.

I can't find any vid with a druid dropping his flight form while flying vertically though, so it might very well be that vertical momentum was ignored back in tbc/wotlk. If so, you would expect a druid flying straight down and dropping flight form to shoot forward horizontally at 280% speed. If not, the druid will drop straight down. Like I said, I'm unsure.

**Comment by blzee** [comment]
Those videos are from a private server just for future reference, you can barely tell due to the low quality of the video but when it first starts playing, there’s a server message. BUT the good news is, I found a source after digging for a bit and it’s reliable. The druid is indeed supposed to keep momentum aftering coming out of flight form. Thank you for your report, I’ll forward to a dev.
