### ISSUE TITLE
90 % AoE dmg reduction missing from hunter pets

### ISSUE THREAD

**Issue by NextiZ** [OmegaWoWeu/Decades#75]
Description: All pets should have 90% aoe dmg reduction, as it was back in the time on retail. Without that,  it is a pain to keep alive ur pet. Seems like only hunter pets are in lack of this avoidance.

How to reproduce bug: Just test it in naxx, Heigan.

How it should work: 90% aoe dmg reduction

Screenshots: -

Relevant AddOns used: -

Source: ingame

**Comment by MarceloTheOne** [comment]
Can't reproduce this issue, works correctly on Heigan.
