### ISSUE TITLE
Conflagrate delay

### ISSUE THREAD

**Issue by JonasD92** [OmegaWoWeu/Decades#77]
Description:
Conflagrate is not useable immediatly after immolate is up on target, there is about half a second delay, bumping the destruction damage rotation and giving time in pvp to dispellers to get rid of Immolate.
How to reproduce bug:
Cast Immolate on any mob and spam Conflagrate, as Immolate cast time equals the global CD you should be able to immediatly use it, but the game says you can't. It can also be seen that the Conflagrate icon stays greyed after the Immolate cast for half a second. 
How it should work:
You should be able to use Conflagrate as soon as Immolate is up on the target.
Screenshots:
![wowscrnshot_022019_184603](https://user-images.githubusercontent.com/22962739/53112728-397a3480-3540-11e9-942a-fa828d62e0de.jpg)

Relevant AddOns used:

Source:

**Comment by OmegaWoWeu** [comment]
So you mean that Conflagrate should not be on the GCD?

I've tried finding sources online that say Conflagrate is/isn't on the GCD, but I haven't been able to find any.

Please attach some sources.

**Comment by JonasD92** [comment]
My apologies, it's not the GCD, but there is like a hidden travel time for Immolate. It is not documented in any Blizzard change log, which is weird, but there are old retail forum posts about what to cast during the Immolate-Conflagrate delay and it can also be seen on old warlock movies(ex. Drakedog 9). So the Conflagrate lag is a blizzlike feature. 
Please consider my ticket invalid.
