### ISSUE TITLE
Encoding bug in all NPCs, quests etc with french client

### ISSUE THREAD

**Issue by RodaxQA** [OmegaWoWeu/Decades#78]
Description: 
I'm a french player with a french client. But in all quests, NPC names, etc... I have an encoding problem! Like if like if there was no utf8 encoding or something in database

Normally, translations should be in database

How to reproduce bug: Log in with french client

How it should work: By example for "Master", it should be "Maître" but it's "MÃ®tre"

Screenshots: https://imgur.com/a/GQedIDW

Relevant AddOns used: - 

Source:

**Comment by RodaxQA** [comment]
Any news? In an other (not french) private server I haven't the issue.

**Comment by OmegaWoWeu** [comment]
Language packs were updated If this will happen again please report it. 
-Bliss

**Comment by RodaxQA** [comment]
You really updated it ? https://imgur.com/a/sX4ZSyy
