### ISSUE TITLE
Unable to mount using gnome/dwarf mechanostrider in Stormwind

### ISSUE THREAD

**Issue by gliffs** [OmegaWoWeu/Decades#8]
Description: When trying to mount up in SW as a gnome using any of the mechanostriders the character *poofs* like normal when finished casting, except the character never actually mounts. Maybe a 1/10 success rate. Untested in other cities, but tested both with my own character(s) and my wife's on a separate account both with and without addons enabled.

How to reproduce bug: Attempt to mount up in SW anywhere

How it should work: Character mounts

Screenshots: https://i.imgur.com/D3AKpB6.jpg https://i.imgur.com/Kw11XuQ.jpg

Relevant AddOns used: 

Source:

**Comment by m98blk** [comment]
I can't tell from your screenshots, but if you're using the new model pack from warmane or a similar source, try disabling that first, it breaks mounting for gnomes among other things.

**Comment by OmegaWoWeu** [comment]
This bug is WoD models related.
