### ISSUE TITLE
Razorgore won't break eggs.

### ISSUE THREAD

**Issue by comatosed** [OmegaWoWeu/Decades#80]
Description: Tried doing BWL for the fetishes but we couldn't break the eggs with Razorgore, the skill itself works and put the fire effect on the ground but nothing happens to the eggs.

How to reproduce bug: Go in to BWL and try breaking eggs while controlling Razorgore

How it should work: The skill should break the eggs one by one.

Screenshots: Doesn't have one

Relevant AddOns used: None relevant for the issue.

Source: Me?

**Comment by Grievuuz** [comment]
Did you try killing him? On other projects the lazy method has been to make him actually die if killed outright. Maybe that works here as well.

**Comment by OmegaWoWeu** [comment]
Currently "hotfixed" removing the doors that prevent the player from accessing the rest of the raid, making Blackwing Lair doable past Razorgore.

Razorgore will be skippable until we fix his egg issue.

**Comment by Grievuuz** [comment]
Very cool that you care about "outdated" content to make an effort trying to make it work. I like it.
