### ISSUE TITLE
Icecrown Quest "... All The Help We Can Get."

### ISSUE THREAD

**Issue by Priis666** [OmegaWoWeu/Decades#84]
Description: You can't talk to Thassarian on the Skybreaker and turn in the quest. I've talked to another player, who had the same issue at the same moment. Relogging didn't work, aborting the quest and accepting it again didn't work either. 
Since it's the prequest to the Knights of the Ebon Blade, it's a little bit annoying.
The quest worked for a friend just a day ago.

How to reproduce bug: Get the quest and try turning it in.

How it should work: You should be able to turn in the quest.

Screenshots:

Relevant AddOns used:

Source:

**Comment by NathanNatNat** [comment]
didnt have this issue myself, done all the available quests in icecrown.

**Comment by Jadgel** [comment]
I have the same issue and noticed that when you first accept the quest from High Captain Justin Bartlett you get an "Objective Complete" banner on your screen (as soon as you accept the quest). This might have something to do with it? Thanks.

**Comment by blzee** [comment]
Tested on both my characters ingame, works for me. Try deleting your cache and retryin, also disable addons and test.
