### ISSUE TITLE
Staff is missing. Can you help pls?

### ISSUE THREAD

**Issue by xxDreamerxx** [OmegaWoWeu/Decades#85]
Description: After defeating the final dragon boss in Oculus hc dungeon, i won by rolling the Staff of Draconic Combat. The items doesn't appear in my bag. 

How to reproduce bug: I was dead just few seconds before killing the boss but i didn't released my soul. I still was inside the dungeon when the item rolls are started then people started left because dungeon was completed. 

How it should work: The item should appear in my bag, i miss it.

Screenshots: http://i68.tinypic.com/11b13zd.jpg

Relevant AddOns used: Bartender, healbot, carbonite, gearscorelite, chatter, gatherer

Source:

**Comment by blzee** [comment]
Your bags were most likely full at that time, if the issue happens again, make another report. No one else has reported anything similar.
