### ISSUE TITLE
No Mercy for the Merciless Quest

### ISSUE THREAD

**Issue by The-Apostle** [OmegaWoWeu/Decades#86]
Description:
The quest will not gain any progress, even though I have killed multiple Horde.

How to reproduce bug:
Pick up the quest and kill Horde in wintergrasp and even though I gain honorable kills I don't gain any progress on the quest, it might require a lot of people attacking the horde for the bug to work, though I haven't gained progress on honrable kills I have gotten with few people.

How it should work:
Every honorable kill should give progress on the quest.

Screenshots:
![image](https://user-images.githubusercontent.com/47987576/53357534-0233cb00-3926-11e9-9e92-7b9120a1f931.png)
I hadn't killed many Horde before picking up the quest but now I have 46 kills after completing 2 wintergrasps:
![image](https://user-images.githubusercontent.com/47987576/53357580-1f689980-3926-11e9-9623-6d5bcfc39159.png)

Relevant AddOns used:

Source:

**Comment by blzee** [comment]
It works, done it multiple times. Abandon quest, close client & delete cache, log back in and try again.
