### ISSUE TITLE
[Quest]  [...All the Help We Can Get.] & [Npc] thassarian

### ISSUE THREAD

**Issue by Bordoo** [OmegaWoWeu/Decades#87]
Description:
in order to compelete this quest you must talk to Npc named  thassarian to compelete the quest 
 [...All the Help We Can Get.] ..but you can't interact with him. so you can not give in the Quest .

Already recived several reports about people cant get the quest [it's all fun and games] from him either

How to reproduce bug: just get the quest [...all the help we can get] and you cant take in the quest Or if you already have a quest from hin simply abondon it : you cant retake it

How it should work: he should take in the quest and players should be able to interact with him

Screenshots:
![wowscrnshot_022519_230513](https://user-images.githubusercontent.com/47177389/53363756-8a2fca00-3952-11e9-944f-27eda3a75c3e.jpg)

Relevant AddOns used:

Source:

**Comment by Jadgel** [comment]
How was this one resolved?
