### ISSUE TITLE
Lightwell not working

### ISSUE THREAD

**Issue by Illuma95** [OmegaWoWeu/Decades#88]
Description: If somebody clicks on a Lightwell and gets the HoT they're not able to reuse it after the HoT wore off. 

How to reproduce bug: Summoning the Lightwell and clicking it once renders it unusable.

How it should work: You should be able to click on the Lightwell as many as 10 times. Yet you can only use it once.

Screenshots: https://imgur.com/a/ItQE7sc
You can see in the first screen that I'm able to click it. In the second screen I used up 1 charge. In the third screenshot I can't use the Lightwell anymore and the mousecurser changed from the gear icon back to the hand, indicating that I can't use the Lightwell again. 

Relevant AddOns used: It has nothing to do with any Addons. It didn't work before I used Addons, too. I frequently ask people in dungeons if they have the same problem as I do and it seems that other people aren't able to use it more than once either.

Source: anecdotal

**Comment by blzee** [comment]
Works fine when I tested it, any proof you can provide?

**Comment by Illuma95** [comment]
I explained exactly what was wrong with it. I even sent screenshots. What
more proof do you need? If you use it and try to click on it again it won't
work anymore unless somebody else clicks on it. Have you actually tried it
as I explained or did you only click on it once?

Am Do., 14. März 2019 um 18:26 Uhr schrieb blzee <notifications@github.com>:
