### ISSUE TITLE
[Quest] all the help we can get , Thassarian 

### ISSUE THREAD

**Issue by Majachie** [OmegaWoWeu/Decades#89]
Description: Thassarian is not popping up in the database leading to the quest all the help we can get not being able to be finished

How to reproduce bug: Go to talk thassarian on the ship in icecrown

How it should work: You talk to him, and you turn in the quests

Screenshots:

Relevant AddOns used:

Source:

**Comment by Jadgel** [comment]
Also have the same issue...just can't talk to him to complete the quest
