### ISSUE TITLE
Wintegrasp Guards Missing

### ISSUE THREAD

**Issue by Icewag** [OmegaWoWeu/Decades#90]
Description: Missing Wintergrasp Champions NPC

How to reproduce bug: Enter WG at any time

How it should work: Missing Champions of Defending Side on North Side of Bridges, also missing Champions of Attacking Side on Westpark & Easpark Vehicle Workshops

Screenshots: https://imgur.com/a/gJyVuO7

Relevant AddOns used: Irrelevant to the Issue

Source: Memory and Wowhead Link with Map of this NPC's : 
[https://www.wowhead.com/npc=30739/warsong-champion](url)
[https://www.wowhead.com/npc=30740/valiance-expedition-champion](url)

**Comment by blzee** [comment]
Thank you for your report
