### ISSUE TITLE
[Paladin] Judgement and seals interaction broken

### ISSUE THREAD

**Issue by Schwulmeister** [OmegaWoWeu/Decades#91]
Description: Paladin seals are proccing off Judgement. Judgement is a spell that uses melee hit rating for calculations, and not an actual melee attack, therefore seals should not apply to it. Only Seal of Righteousness should proc from Judgement. Additionally, Paladin Judgement procs on-melee hit effects off npc's and players, for example Frost Armor.

How to reproduce bug: Pick up a Paladin, use Seal of Command, stand at max range from a practice dummy or an attackable NPC and cast Judgement. There will be two numbers popping up, one for the Judgement spell and one for the Seal proc.

How it should work: Seals should never proc off spells no matter what hit they use for calculations. Abilities that proc Seals are white melee, Crusader Strike, Divine Storm, Hammer of the Righteous, Shield of Righteousness. Judgement and similar spells that utilise melee hit rating are not melee attacks and shouldn't be treated as such.

Screenshots: https://imgur.com/a/b16ZYDV https://imgur.com/a/W8REDnG https://imgur.com/a/7v85aon  https://imgur.com/a/QvfV1QZ https://imgur.com/a/QfBgMzi https://imgur.com/a/ffbVhof

Relevant AddOns used: Skada

Source:

**Comment by alecagha** [comment]
Judgements are considered a ranged melee attack as they should be. It’s supposed to proc seals. It works like this on every wrath server. If it didn’t proc seals then why would it be top in the priority list for  ret paladins? 

If SoW didn’t proc off judgements, it’d be putting holy paladins at a serious mana disadvantage.

From the 3.2 patch notes:
“Judgements: Some of these attacks were considered ranged and some melee. They are all now considered melee attacks that can't be dodged, parried or blocked.”

**Comment by Schwulmeister** [comment]
The problem is that damaging seals proc off judgements while they shouldn't.

**Comment by alecagha** [comment]
> The problem is that damaging seals proc off judgements while they shouldn't.

Where do you get this idea from? This is how all seals should work with all judgements. You need to provide some evidence of how a certain mechanic should be working (e.g. patch notes, archived forum posts, wiki articles) if you want to make a case for your bug report, instead of just your own testimony.

**Comment by blzee** [comment]
Invalid report, seals are working as intended. Not sure what those screenshots were for as well, those combats logs are correct.
