### ISSUE TITLE
[Invalid][Spell] Pin Effect of Crab pet

### ISSUE THREAD

**Issue by mclgv** [OmegaWoWeu/Decades#93]
Description: Pin Interruption mechanic not correctly working on npcs or players.

How to reproduce bug: Pick up a crab with pin ability use it on a caster npc or duel with caster player.

How it should work: Ability must interrupt from cast or any movement affect until ability is faded.

Screenshots: 1)http://tinypic.com/r/2jcsoc5/9 2)http://i64.tinypic.com/2ahfme1.jpg

Relevant AddOns used: None

Source: This mechanic was working on true way with 4.30 patch
https://www.wowhead.com/spell=50245/pin#comments

**Comment by blzee** [comment]
Working as intended, pin just renders the target in place, they can still attack. 

Pin is one of the pet abilities that only crabs can use. It allows the crab to squeeze a target in place for 4 seconds.

https://wow.gamepedia.com/Pin
