### ISSUE TITLE
NPC bugged countering

### ISSUE THREAD

**Issue by spana1993** [OmegaWoWeu/Decades#97]
when fighting NPC-s (im tested in STV Valley) and im use stun (im use paladin stun) and im casting something spell (exorcism, holy light etc..) the NPC what can countering, CS me meanwhile stunned. I think this global problem.
Sry for english

Castiel

**Comment by RodaxQA** [comment]
+1, can disarm too after a kidney.. Wtf

**Comment by zoneqt** [comment]
I opened cheapshot on another rogue , he disarmed me in first second of stun, its also possible to use vanish in 1st second of cheapshot, i hope this will be fixed soon because its impossible to play rogue.

**Comment by RodaxQA** [comment]
I think your behavior is normal in pvp (I already have encountered this "feature" on old Arena T****** pvp server) for the delay, you can look in youtube some rogue vs rogue 1v1, but NPC just can CS you in the middle of a stun, that is a bug
