### ISSUE TITLE
Parry bug in mount

### ISSUE THREAD

**Issue by spana1993** [OmegaWoWeu/Decades#98]
This bug a litte but funny. When you running with mount and NPC hit you, can PARRY. How? Learn me! :D  Your weapon in your back Kenobi ;)
Sry for my english.

Castiel

**Comment by ghost** [comment]
Can't find any info on this. I don't think being mounted prevents you from parrying.

Edit : seems to be intended https://us.battle.net/forums/en/wow/topic/15701392031
