### ISSUE TITLE
death knight duel spec bug

### ISSUE THREAD

**Issue by AsimpleMook** [OmegaWoWeu/Decades#99]
Description: death knights are able to get duel spec without paying before leaving starting area, 

How to reproduce bug: complete the quest chain up to reporting to scourge commander thalanor, then go to any of the class trainers and ask about duel spec, no talent points used

How it should work: gotta pay 1000g?

Screenshots:
![wowscrnshot_030119_114023](https://user-images.githubusercontent.com/48136469/53662496-dd866e80-3c17-11e9-838c-f1f1a1d2ff9a.jpg)

![wowscrnshot_030119_114005](https://user-images.githubusercontent.com/48136469/53662561-0a3a8600-3c18-11e9-8ca1-b81d9d14e06f.jpg)
![wowscrnshot_030119_114042](https://user-images.githubusercontent.com/48136469/53662564-0c044980-3c18-11e9-89f0-50d03339c5c8.jpg)

Relevant AddOns used: none used

Source:

**Comment by OmegaWoWeu** [comment]
Alliance does have free dual spec, so it was intended.
